### ISSUE TITLE
pool.exec not compatible with ES6 class syntax

### ISSUE THREAD

**Issue by rahul22048** [josdejong/workerpool#104]
I am using ES6 class syntax. I have initialised my pool object inside the class constructor.
But when i am trying to dynamically offload the function with below syntax :-

this.pool.exec(getUserInside,[userId,apiKey,behanceUrl]); it is giving me error getUserInside not defined. when i replaced it with below synxtax:-

this.pool.exec(this.getUserInside,[userId,apiKey,behanceUrl]); it is again giving me different error.

But when i replaced everything in my code with old syntax without class structure everything worked fine.

Is workerpool not compatible with ES6 syntax

**Comment by josdejong** [comment]
I'm not sure how I can reproduce your issue. Can you give a complete (minimal) code example?

Can your issue be similar to #68?

**Comment by rahul22048** [comment]
Yes exactly similar to #68 .

**Comment by josdejong** [comment]
So does that explain the problem for you then? Can we close this issue?

**Comment by rahul22048** [comment]
Yes you can close the issue.

**Comment by josdejong** [comment]
:+1:
