### ISSUE TITLE
Is streaming to proxy supported?

### ISSUE THREAD

**Issue by haimomesi** [josdejong/workerpool#108]
I've been using a standalone Worker in my Node.js app.

My worker created a zip stream and streamed the chunks via Worker's parentPort.postMessage like so:

`zip.generateInternalStream({ type: 'uint8array', compression: 'DEFLATE' }).on('data', (streamData, metadata) => { parentPort.postMessage(streamData)`

The main file had:
`const worker = new Worker('../../libs/worker/zip.worker.js');
worker.on('message', message => { socket.emit(message)}`

Using workerpool, how would one achieve this flow? there's is no documentation regarding the native Worker `.on()` function.

Thank you,
Haim

**Comment by josdejong** [comment]
There is nothing build in to support streams, I don't think it will work right now.
