### ISSUE TITLE
Export maximum number of workers supported

### ISSUE THREAD

**Issue by natlibfi-arlehiko** [josdejong/workerpool#11]
Exporting the maximum number of workers supported would be a nice addition to workerpool.

Workerpool can queue exec calls if there aren't any workers available but sometimes you want to know that beforehand so that you don't have to pull data in memory (From some external resource) until there are resources to process it.

Also, since Workers are not in Ecmascript specification and there is no cross-platform way to get the maximum number of available workers workerpool might as well provide this feature.

Implemented [here](https://github.com/natlibfi-arlehiko/workerpool/tree/env-max-workers).

**Comment by natlibfi-arlehiko** [comment]
Actually, the exported property will default to **4**, if the browser doesn't support *window.navigator.hardwareConcurrency*. If the feature isn't implemented the value should probably be *undefined* (And the default **4** should only be used internally by workerpool)

**Comment by natlibfi-arlehiko** [comment]
Done. Now the implementation returns undefined if the maximum number of workers cannot be determined.

**Comment by josdejong** [comment]
Interesting idea to expose the determined number of cpus, and neat to move this logic into `environment.js`. Few suggestions:

- I think `maxSupportedWorkers` should be renamed to `cpus` since that's what the number is. This should indeed return undefined when it couldn't be determined
- We can export both `platform` and `cpus` to make this complete
- I think you can simply create these two environment parameters as constants rather than getter functions, they will never change, i.e. environment.js can be simplified to:

  ```js
// used to prevent webpack from resolving requires on node libs
var node = {require: require};

// determines the JavaScript environment: browser or node
exports.platform = (typeof window !== 'undefined') ? 'browser' : 'node';

// determine the number of cpus (will be undefined when the number couldn't be determined)
exports.cpus = (exports.platform === 'browser')
      ? window.navigator.hardwareConcurrency
      : node.require('os').cpus().length;  // call node.require to prevent `os` to be required when loading with AMD
```

**Comment by natlibfi-arlehiko** [comment]
> I think maxSupportedWorkers should be renamed to cpus since that's what the number is

Well, [not necessarily](https://developer.mozilla.org/en-US/docs/Web/API/NavigatorConcurrentHardware/hardwareConcurrency#Value):

> The browser may, however, choose to report a lower number of logical cores in order to represent more accurately the number of Workers that can run at once, so don't treat this as an absolute measurement of the number of cores in the user's system.

> We can export both platform and cpus to make this complete

If the `platform` property is going to be exported the value returned for workers needs to be changed. Currently __*node*__ would be returned because workers don't have __*window*__ available. If we use __*browser*__ for both the main thread and workers the following code needs to be changed: https://github.com/josdejong/workerpool/blob/master/index.js#L20

How about returning __*browser-worker*__ for workers?

**Comment by josdejong** [comment]
About the name: if you're more happy with a name like `hardwareConcurrency` instead of `cpus` that's ok with me. I think `cpus` is a clear name though. At least `maxSupportedWorkers` would be misleading since you can perfectly fine create 1000 Workers on a 4 core machine.

Just looking at the code you're pointing to (index.js#20) - I would say you're right though I don't get why stuff currently works at all since this behavior is already there in the current code. Guess I'm overlooking something obvious.

**Comment by josdejong** [comment]
I think we have two orthogonal things here that we should keep separated: 

- running in a node.js environment vs the browser
- running in the main thread or in a worker/child_process

**Comment by natlibfi-arlehiko** [comment]
> I don't get why stuff currently works at all since this behavior is already there in the current code. Guess I'm overlooking something obvious.

I think it's because webpack's require is used here and the module is pulled from the same file.

Maybe `platform` should only return either __*node*__ or __*browser*__ and there'd be a separate property to tell if the code is running in a maim thread or not?

**Comment by natlibfi-arlehiko** [comment]
All right. New implementation is [here](https://github.com/natlibfi-arlehiko/workerpool/tree/environment-rewrite).

Now the following properties are available: **platform**, **is_main_thread** and **cpus**.

Also, I removed the [block](https://github.com/josdejong/workerpool/blob/master/index.js#L20) which was trying to include the embedded worker in **worker.js**. It didn't work and is not needed since webpack is used for browser builds anyway.

**Comment by josdejong** [comment]
That looks neat! 

One small detail: I think it would be more consistent to give the properties lower camel case naming: `isMainThread` instead of `is_main_thread`.

I would love to see a PR with your work :)

**Comment by natlibfi-arlehiko** [comment]
#13

**Comment by natlibfi-arlehiko** [comment]
#14
