### ISSUE TITLE
isMainThread is incorrect when using node worker_threads

### ISSUE THREAD

**Issue by forivall** [josdejong/workerpool#121]
My current workaround:
```diff
-if (!workerpool.isMainThread) {
+let isMainThread = workerpool.isMainThread;
+if (isMainThread) {
+  try {
+    // tslint:disable-next-line: no-var-requires
+    const workerThreads: typeof import('worker_threads') = require('worker_threads');
+    if (!workerThreads.isMainThread) {
+      isMainThread = false;
+    }
+  } catch (err) {} // tslint:disable-line: no-empty
+}
+
+if (!isMainThread) {
```

Repro is to just `console.log(workerpool.isMainThread)` with a worker when using worker_threads.

**Comment by josdejong** [comment]
Thanks for reporting this issue Emily. Turns out the `isMainThread` property was never updated to reckon with the (recent) support for `worker_threads`. Working on a fix...

**Comment by josdejong** [comment]
This should be fixed now in `v5.0.4`, can you give it a try @forivall?

**Comment by forivall** [comment]
Works! Thanks for the quick turnaround.

**Comment by josdejong** [comment]
You're welcome :) thanks for the confirmation.
