### ISSUE TITLE
Transfer Array Buffers

### ISSUE THREAD

**Issue by munawarb** [josdejong/workerpool#132]
Hi,
In standard workers, one can transfer memory using typed arrays. I haven't been able to find how to do this using this workerpool module. I looked at #3 but it's been two years since an update to it.

Is there any way to move an array back to the parent process? I'm dealing with very large arrays and copying the memory over through serialization is both time consuming and prone to OOM errors.

**Comment by josdejong** [comment]
Thanks for your input Munawar. transferring objects and buffers is indeed not yet implemented, though it would be a great addition. There is no easy workaround for it that I can think of right now.

**Comment by munawarb** [comment]
Hi @josdejong,
Thanks for the response! This will be a nice addition to the module.

**Comment by ahkohd** [comment]
😭🥺😩

**Comment by ahkohd** [comment]
> Thanks for your input Munawar. transferring objects and buffers is indeed not yet implemented, though it would be a great addition. There is no easy workaround for it that I can think of right now.

Hmm, I have this idea in my head. 🤷

Say we have a dedicated web worker (X) for holding transferable objects for the moment.

You invoke pool.exec()
The transferable object you passed instantly gets transferred to worker X which also keeps track of which job owns the transferable object.
When your job is ready for processing by another web worker say (Y).
Worker Y sends a message to worker X to ask if you have any transferable object intended for the job it's about to run.
If yes, worker X transfers the transferable object to worker Y.

**Comment by josdejong** [comment]
Let's please continue any discussion in #3
