### ISSUE TITLE
Initialising workers with extra data

### ISSUE THREAD

**Issue by sbrl** [josdejong/workerpool#139]
I need to initialise the workers in my pool with some configuration data from the main controller process. Is it possible to pass some extra state information to a worker? For example:

```js
// ......
let pool = workerpool.pool({
     state_info: { foo: 5, bar: "some_string" }
});
```

```js
// worker
console.log("I have state info:", workerpool.state_info);
```

or something?

**Comment by josdejong** [comment]
Thanks for sharing your idea @sbrl. Is this the same what's discussed in #65 ?

**Comment by sbrl** [comment]
Ah, that does sound similar! I'll make a comment over there.

**Comment by sbrl** [comment]
Ah, that does sound similar! I'll make a comment over there.
