### ISSUE TITLE
Cannot call functions outside the method when transpiled from TS to JS

### ISSUE THREAD

**Issue by juicetin** [josdejong/workerpool#142]
Example code snippet in a ts file:
```
const myFunc = async ({ foo }) => {
   await something(foo);
   await anotherThing(foo);
};
...
const problematicFunc =  async () => {
   await pool.exec(myFunc, [{ foo: 'bar'}])
}
```

After transpiling the code to JS and running it, there is a `__awaiter is not defined` error. A similar error appears for any use of imports, function calls, etc. inside the `problematicFunc` function.

All the things that says are not defined are in fact defined - but they simply are not variables _inside_ the function itself.

**Comment by josdejong** [comment]
That's correct (though this is not TypeScript specific), [see docs](https://github.com/josdejong/workerpool#offload-functions-dynamically):

> Note that both function and arguments must be static and stringifiable, as they need to be sent to the worker in a serialized form. 

See also #28

**Comment by serg06** [comment]
I was able to solve this by creating a static workerpool from its own file.
