### ISSUE TITLE
The result of worker's returning Buffer is different among process and thread

### ISSUE THREAD

**Issue by RogerKang** [josdejong/workerpool#153]
Let see a simple demo about child process and worker_threads on Buffer message transforming:
```
// call worker in child_process and worker_threads separately
let child_process = require('child_process');
let processWorker = child_process.fork('./worker.js');
processWorker.on('message', (msg) => {
  console.log('msg from child process', msg);
});
const { Worker } = require('worker_threads');
const threadWorker = new Worker('./worker.js');
threadWorker.on('message', (msg) => {
  console.log('msg from worker_thread', msg);
});
```

```
// worker
const {
  Worker,
  isMainThread,
  parentPort,
  workerData,
} = require('worker_threads');
if (isMainThread) {
  process.send(Buffer.from('abc'));
} else {
  parentPort.postMessage(Buffer.from('abc'));
}
```

And the result is different:
```
msg from worker_thread Uint8Array [ 97, 98, 99 ]
msg from child process { type: 'Buffer', data: [ 97, 98, 99 ] }
```

That means where you change your workerpool workerType from process to thread or contrarily, you probably face an issue if you transfer Buffer data among worker and main program.

And my focus is: 
Actually it can not  be blamed to workerpool, but should we handle this situation in workerpool to avoid this(But it will cause new problem because definitely someone have handle this difference in their code)?
And at least we should Doc it to warn developer to take care of workerType changing and do enough test.

**Comment by josdejong** [comment]
That is a very good point Roger. 

We could try to wrap buffers in a unified API, but I'm afraid that will be tricky and does not give you the low level control that you need when working with buffers. And there could be more of these API differences.

I've added explanation about this in the README now, see https://github.com/josdejong/workerpool/commit/eaba36bf4c901cfe66db5fecdb2736eb2bbeac75. Do you think that will do?
