### ISSUE TITLE
For some reason my worker refuses to run

### ISSUE THREAD

**Issue by lovgrandma** [josdejong/workerpool#157]
I am running nodejs npm version 6.14.4
My code was originally running on an older build of nodejs but when I wanted to use the thread option I was required to update to a newer nodejs.

In this new version of nodejs, my workers dont seem to work at all. Im pretty sure I am using the correct syntax, but Im getting nothing. I must be making some error with the pool.exec method. See code below

Worker file processvideo.js
```
const workerpool = require('workerpool');

const convertVideos = async function(i, originalVideo, objUrls, generatedUuid, encodeAudio, room, body, io) {
   console.log("convertVideos worker running?"); // nothing comes up, nothing else runs
   // do lots of stuff
}
workerpool.worker({
    convertVideos: convertVideos
});

exports.convertVideos = convertVideos;
```

Master file
```
const workerpool = require('workerpool');

const videopool = workerpool.pool(__dirname + '/processvideo.js');

module.exports = function(io) {   
   const prepareUpload = async (req, res, next) => {
      // do some things
      videopool.exec('convertVideos', [i, originalVideo, objUrls, generatedUuid, true, room, body, null])
         .then(function (result) {
            console.log("Video conversion result" + result);
         });
   }
}
```

**Comment by lovgrandma** [comment]
I have found out my error. Method was not defined in the way workerpool was expecting. 
Needed to put: 
```
async function convertVideos(arguements) {
```
instead of what I had there.

**Comment by josdejong** [comment]
:+1:  good to hear the issue is solved
