### ISSUE TITLE
Running pool.exec inside loop

### ISSUE THREAD

**Issue by msanandrea** [josdejong/workerpool#162]
Hey! First of all thanks for this great library and sorry in advance for my ignorant question. This ain't an issue, more like a doubt of how the workerpool internally works. I've an array of users, which they've to run a certain task in parallel. So, my code will look like this...

```
const pool = workerPool.pool({ maxWorkers: cpuCount });
users.forEach(user => {
    pool.exec(TASK, [user]).then((result) => {
        console.log(result);
    });
});
```
From what I understood, that will assign a `Worker` for the first 4 users (cpuCount  = 4), queue the other ones, and start assigning the queued users to those workers as they are released, right? Does that mean that each user will always run on his own "Thread"?

I also read on another question, that you could create as many workers as you wish. So, I can theoretically do this `const pool = workerPool.pool({ maxWorkers: users.length});` right? What will be the drawback for that? Too much resoruce consuming in order to generate that huge amount of `Workers`?

Thanks

**Comment by josdejong** [comment]
Thanks @msanandrea. 

You can test the behavior quite easily by creating a fake task containing a timeout of say 5 seconds, and then start 10 of those tasks and see when they return. Each worker processes 1 task at a time. When you add a task, and there is an idle worker, it will start immediately. If there is no idle worker, the task will be added to the queue. As soon as a worker is done with a task, it will pick the next task from the queue (if any).

You can configure the number of workers as you like. Creating a worker costs some time and requires memory, so there is a balance somewhere for the "ideal" number of workers. What is "ideal" depends on the use case.

**Comment by msanandrea** [comment]
@josdejong thanks for the quick response!

So, independently the amount of `Workers` I create (`cpuCount` or `users.length`) I can be sure that each task will run on a separate thread? as each task will always run on its own `Worker` right?

**Comment by josdejong** [comment]
Correct, every worker runs only a single task at a time. You cannot control though on which worker a certain task is executed: it's executed on the first idle worker.

If you have say 100 users and you want to make sure that non of the users can block work for the other users, using a single pool with 100 workers gives no guarantees though: each user can create many tasks which will be queued on the single pool. If you want to make sure of that you can create 100 pools containing 1 worker, and send tasks for a specific user to a single pool dedicated for this user.

**Comment by msanandrea** [comment]
@josdejong I see. I'll try the N-Pools approach then in order to be 100% sure that no User will block another one. Thanks so much for your time!

**Comment by josdejong** [comment]
👍
