### ISSUE TITLE
Question: How trigger a function when all tasks are completed?

### ISSUE THREAD

**Issue by flesicek** [josdejong/workerpool#166]
Hey, 

First of all, thanks for great library.
I'm testing following patter:
1. run multiple tasks in parallel by executing:
```
   pool.exec('longTast', [10])
    .then(function (result) {
      console.log('Result: ' + result);
    })
    .catch(function (err) {
      console.error(err);
    })
```
2. when all the tasks are either completed or error is caught I would like to continue execution.

Question: How to create callback which is called "once" after all tasks are done?

**Comment by josdejong** [comment]
Thanks!

You can wrap all tasks in a `Promise.all(...)` or `Promise.allSettled(...)` (the latter is not supported by IE).
