### ISSUE TITLE
Promise.prototype.finally

### ISSUE THREAD

**Issue by ericman314** [josdejong/workerpool#169]
`Promise.prototype.finally()` was added in Node v10 and is also in most major browsers now. It would be great to have that function available from `pool.exec`. 

Some references:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/finally
https://github.com/tc39/proposal-promise-finally/blob/fd934c0b42d59bf8d9446e737ba14d50a9067216/polyfill.js

**Comment by josdejong** [comment]
Good idea 👍 

Anyone interested in implemented `finally`?

**Comment by adrfantini** [comment]
One thing I noticed is that `exec` actually returns a promise with an `.always()` method available. However, it is not documented as far as I can tell.

**Comment by josdejong** [comment]
That can be refactored I think, it's similar to `finally`
