### ISSUE TITLE
process.send is undefined

### ISSUE THREAD

**Issue by thib3113** [josdejong/workerpool#170]
Hello, I got this error :
Did I need to start the process in another process to populate the process.send ?
```
node_modules\workerpool\src\worker.js:49
    worker.send = process.send.bind(process);
                               ^
TypeError: Cannot read property 'bind' of undefined
    at Object.<anonymous> (node_modules\workerpool\src\worker.js:49:32)
    at Module._compile (internal/modules/cjs/loader.js:1201:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1221:10)
    at Module.load (internal/modules/cjs/loader.js:1050:32)
    at Function.Module._load (internal/modules/cjs/loader.js:938:14)
    at Module.require (internal/modules/cjs/loader.js:1090:19)
    at require (internal/modules/cjs/helpers.js:75:18)
    at Object.worker (node_modules\workerpool\src\index.js:20:16)
```

I'm using node js v14.5.0 .

It seems that 
```
worker.send = (process.send || function () {}).bind(process);
```
doesn't crash for the moment .

**Comment by josdejong** [comment]
> Did I need to start the process in another process to populate the process.send ?

No, this is a built-in method. It is only available inside a child_process though, not the main node.js thread. Maybe you're loading the library not in the right way?

**Comment by thib3113** [comment]
maybe, I doesn't know ...
I try to use this : https://github.com/josdejong/workerpool#offload-functions-dynamically
But registering the functions on other parts of the app . ( with the workerpool.worker() ) . 

In fact, I doesn't really need to do things in differents threads, I'm just searching something to send task to a workerpool, and the workers will process them with a limit ( example : 5 per 5 ) . ( my tasks just do webrequests ) . 
Maybe this lib is not what I search ?

( for the moment, I do all this part manuallly )

**Comment by josdejong** [comment]
> In fact, I doesn't really need to do things in differents threads, I'm just searching something to send task to a workerpool, and the workers will process them with a limit ( example : 5 per 5 ) . 

This is indeed what `workerpool` can help you with. 

> ( my tasks just do webrequests ) .
> Maybe this lib is not what I search ?

If you only do webrequests and no CPU heavy calculations, there is no reason though to offload functionality to a workerpool, in that case you can use some queuing library.

**Comment by thib3113** [comment]
> If you only do webrequests and no CPU heavy calculations, there is no reason though to offload functionality to a workerpool, in that case you can use some queuing library.

in fact, the workerpool, is a way (for me), to limit the concurrent request to a same site .

Actually, I use custom "workers" (async.js call them "worker"s ), to call custom function ... And I think, this lib can help me for this, but maybe not .

**Comment by josdejong** [comment]
To limit concurrent requests you can use a much simpler solution like https://caolan.github.io/async/v3/docs.html#queue or something like that.

**Comment by thib3113** [comment]
> To limit concurrent requests you can use a much simpler solution like https://caolan.github.io/async/v3/docs.html#queue or something like that.

yes, I know, it's what I've done temporary because this library doesn't seems to work . But the coalan approach is to use always the same function for a queue, and not a pool of functions . So, I need to write some things, to store functions, and the common worker function will take the function in the pool of functions ...

So, it's why I've think you're approach is maybe better, and maybe more futurproof, If I wan't to add more functions, that can do more powerfull things . ( the actual project is just a little microservice, but I can try libraries, and see if I can reuse them later )

**Comment by josdejong** [comment]
I'm not sure how I can help you further. Maybe if you create a minimal code example demonstrating how you try to use the library we can see what's going on.

**Comment by thib3113** [comment]
hum, just, if I correctly understand, the function `workerpool.worker`, always need to be used in a dedicated worker ?

And only pool.exec can be used in the same file ? ( first example )

**Comment by josdejong** [comment]
> hum, just, if I correctly understand, the function workerpool.worker, always need to be used in a dedicated worker ?

That's correct.

> And only pool.exec can be used in the same file ? ( first example )

`pool.exec` should be called from the main process.

**Comment by thib3113** [comment]
hum, okay I understand ...

And, how to manage things like if I need to package the app ? In general, they will link all the files with the "require", and need require with string (no var), 
so `workerpool.pool(__dirname + '/myWorker.js');` will not import the file in the package . ( not a feature request )
Is it handled ? Or the packager need to hande a manual import ?

Thanks you for the answer, I will note this If I need this kind of lib next time :)

**Comment by josdejong** [comment]
Good question. Creating a bundle with the worker (or a separate bundle of the worker) requires some work unfortunately.

Example: https://github.com/josdejong/workerpool/tree/master/examples/embeddedWorker
Open issue: https://github.com/josdejong/workerpool/issues/23
