### ISSUE TITLE
How to run multiple tasks?

### ISSUE THREAD

**Issue by lolpez** [josdejong/workerpool#177]
Sorry noob here, so in the example of running a dedicated worker.... how can I run the same task multiple times? What I would like to achieve is to run the same Fibonacci method 1000 times and make sure the worker pool is queuing the tasks.
This is my code and it is not working

**myWorker.js**
```
const workerpool = require('workerpool');
 
// a deliberately inefficient implementation of the fibonacci sequence
function fibonacci(n) {
  if (n < 2) return n;
  return fibonacci(n - 2) + fibonacci(n - 1);
}
 
// create a worker and register public functions
workerpool.worker({
  fibonacci: fibonacci
}); 
```

**MyApp.js**
```
const workerpool = require('workerpool');
 
// create a worker pool using an external worker script
const pool = workerpool.pool(__dirname + '/myWorker.js');
 
// run registered functions on the worker via exec
for (let i = 0; i < 1000; i++) {
       pool.exec('fibonacci', [10])
         .then(function (result) {
           console.log('Result: ' + result); // outputs 55
        })
       .catch(function (err) {
         console.error(err);
       })
       .then(function () {
         pool.terminate(); // terminate all workers when done
       });       
}

```

**Comment by josdejong** [comment]
Your for loop fires off 1000 tasks at the same time, but directly after the first of the tasks finishes, you terminate the pool. That's probably not your intention?

**Comment by lolpez** [comment]
ok I made the changes, is this the correct way to terminate the pool?

const workerpool = require('workerpool');
 
// create a worker pool using an external worker script
const pool = workerpool.pool(__dirname + '/myWorker.js');
 
// run registered functions on the worker via exec
for (let i = 0; i < 1000; i++) {
       pool.exec('fibonacci', [10])
         .then(function (result) {
           console.log('Result: ' + result); // outputs 55
        })
       .catch(function (err) {
         console.error(err);
       })
       .then(function () {
           if (pool.stats().pendingTasks === 0 && pool.stats().activeTasks === 0) {
                  pool.terminate()
           }
       });       
}

**Comment by josdejong** [comment]
I think that will work though I would look into awaiting all of the 1000 promises that you create by collecting them in an array and using `Promise.all(...).then(...)`
