### ISSUE TITLE
Trying to eval a class string with a pool 

### ISSUE THREAD

**Issue by scaby2323** [josdejong/workerpool#178]
Hi, I am trying to evaluate a class that is currently a string using a pool like so: 

`const class = "class A { n: number constructor(n) { this.n = n } }`
`const pool = workerpool.pool()`
`const result = pool.exec(eval, [`(${class})`])`

However when I run this I get an "Unexpected identifier" error. I think this is because eval is not stringifiable. 

Then, I was trying to pass my class directly into the exec function but I get an error that this is not a valid method. 

`const class = "class A { n: number constructor(n) { this.n = n } }"`
`const pool = workerpool.pool()`
`const result = pool.exec(class, [])`

Are there any suggestions for a better way to approach this or to be able to convert the class (as a string) to a function using the pool?

**Comment by josdejong** [comment]
For larger workers which have shared code like a class in both the main process as well as in the worker, I think you should create a separate bundle for the worker. See related issue: #189.
