### ISSUE TITLE
TypeError when using @pm2/io

### ISSUE THREAD

**Issue by ericman314** [josdejong/workerpool#193]
When using `workerpool` in a node.js process which also uses [@pm2/io](https://github.com/keymetrics/pm2-io-apm), then about five seconds after running a worker, this error is thrown:

```
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at Object.extractMessagePort (/.../node_modules/event-loop-inspector/utils.js:94:31)
    at /.../node_modules/event-loop-inspector/index.js:45:17
    at Array.forEach (<anonymous>)
    at Object.dump (/.../node_modules/event-loop-inspector/index.js:22:42)
    at Timeout._onTimeout (/.../node_modules/@pm2/io/build/main/transports/IPCTransport.js:34:50)
    at listOnTimeout (internal/timers.js:551:17)
    at processTimers (internal/timers.js:494:7)
```

I am suspecting that this is a bug in @pm2/io, but I'll post it here too in case workerpool might also be responsible.

You can use this to test:

### littleFunction.js

```js
const workerpool = require('workerpool')

function littleFunction(a) {
  return -a
}

workerpool.worker({
  littleFunction
})
```

### testLittleFunction.js

```js
const io = require('@pm2/io')
const workerpool = require('workerpool')

const pool = workerpool.pool(__dirname + '/littleFunction.js')

pool.exec('littleFunction', [5]).then(answer => {
  console.log(answer)
}).catch(ex => {
  console.error(ex)
})

// Keep process running long enough for the error to occur
setTimeout(() => { }, 10000)
```

**Edit: I am using node.js v14.8.0.**

**Comment by josdejong** [comment]
Thanks for sharing this issue.

It would be interesting to see if the issue still occurs when replacing `workerpool` with a simple nodejs `worker_thread`, which is used under the hood by `workerpool`. That would rule out `workerpool` itself when the issue still occurs.

**Comment by ericman314** [comment]
It turns out I was running an older version of @pm2/io. In the latest version the error does not occur, so false alarm.

**Comment by josdejong** [comment]
Ah :smile: that is an easy fix then.
