### ISSUE TITLE
passing Parameters to workers

### ISSUE THREAD

**Issue by freund17** [josdejong/workerpool#2]
It would be cool if you could pass parameters to the workers.
For example beeing able to increase the stack-size would be nice.
Also always passing the parent parameters is a problem, if you are using an IDE like VS Code, because it uses a debug port, which is blocked by the main process, when the worker try to open it (so the workers crash).

**Comment by josdejong** [comment]
Thanks for your suggestions, passing "system level" parameters like stack-size can be useful. Of course the available parameters differ per environment (node.js vs browser).

I'm not sure what issues you mean regarding parent parameters and VS Code, can you elaborate?

**Comment by freund17** [comment]
Well, VS Code starts node with the "--debug-brk=32411" argument, which is needed for debuging. (No idea how it works exactly, but I think it opens that port and waits for debug instructions)
The thing is, by default "child_process.fork(modulePath[, args][, options])" uses the arguments of the parent instance, which means "--debug-brk=32411" will also be copied, which leads to the workers trying to open a port which is already blocked. And so the workers crash.

**Comment by josdejong** [comment]
ah, thanks, now I understand the problem. Weird that these parent arguments are passed the childs, I can't find anything about that in the docs - the docs say that an empty array is passed if the second argument `args` is not provided.

**Comment by freund17** [comment]
There it is: https://nodejs.org/api/child_process.html#child_process_child_process_fork_modulepath_args_options

"execArgv Array List of string arguments passed to the executable (Default: process.execArgv)"

**Comment by josdejong** [comment]
Ah, ok, I was looking at `args`, not at `execArgv`.

See also: http://stackoverflow.com/questions/19252310/how-to-fork-a-child-process-that-listens-on-a-different-debug-port-than-the-pare

**Comment by josdejong** [comment]
This issue should have been fixed now in `v2.2.1`
