### ISSUE TITLE
Register a async function

### ISSUE THREAD

**Issue by pragmaticivan** [josdejong/workerpool#22]
Would be possible to register a function that returns a Promise ?

**Comment by josdejong** [comment]
Yes, see the async example:

https://github.com/josdejong/workerpool/blob/master/examples/async.js
https://github.com/josdejong/workerpool/blob/master/examples/workers/asyncWorker.js

**Comment by josdejong** [comment]
and docs:

https://github.com/josdejong/workerpool#worker
