### ISSUE TITLE
ReferenceError: require is not defined in workers

### ISSUE THREAD

**Issue by adrfantini** [josdejong/workerpool#231]
Hi!
I am using `workerpool` to carry out some work on separate workers. However, it seems that inside workers I cannot use `require` to load some necessary modules. See this MRE:
```js
const workerpool = require('workerpool');
const pool = workerpool.pool();
function req(a, b) {
    const r = require('workerpool');
    return a+b;
}
pool.exec(req, [3, 4]).then(function (result) {
    console.log('result', result);
}).catch(function (err) {
    console.error(err);
})
```
The error it gives:
```
> ReferenceError: require is not defined
    at req (eval at run (/usr/lib/node_modules/workerpool/src/worker.js:100:11), <anonymous>:2:5)
    at Function.eval (eval at run (/usr/lib/node_modules/workerpool/src/worker.js:100:11), <anonymous>:4:4)
    at Function.run (/usr/lib/node_modules/workerpool/src/worker.js:101:12)
    at MessagePort.<anonymous> (/usr/lib/node_modules/workerpool/src/worker.js:121:27)
    at MessagePort.emit (events.js:311:20)
    at MessagePort.onmessage (internal/worker/io.js:78:8)
```

Any idea how to fix this?

**Comment by josdejong** [comment]
You can use require inside a worker, but in your example you are offloading a function. This has limitations: the function must be standalone. See docs:

https://github.com/josdejong/workerpool#offload-functions-dynamically

> Note that both function and arguments must be static and stringifiable, as they need to be sent to the worker in a serialized form. 

I think your issue will be solved when you create a dedicated worker instead (https://github.com/josdejong/workerpool#dedicated-workers)

**Comment by adrfantini** [comment]
Indeed, this was the issue. Thank you! regarding the docs: to me, that a function should be "static" does not necessarily mean that it cannot load external modules, maybe the docs could be updated. However, I have not much experience with JS so it might just be me. Thanks again!

**Comment by josdejong** [comment]
👍
