### ISSUE TITLE
Third party and its environment

### ISSUE THREAD

**Issue by webbery** [josdejong/workerpool#234]
Hi,
I use a third party and pass it to exec. Then I get the following error:
```
Uncaught (in promise) ReferenceError: NLP is not defined
    at Function.getNouns (eval at run (E:\code\nodejs\civet\node_modules\workerpool\src\worker.js:100:11), <anonymous>:2:5)
    at Function.run (E:\code\nodejs\civet\node_modules\workerpool\src\worker.js:101:12)
    at process.<anonymous> (E:\code\nodejs\civet\node_modules\workerpool\src\worker.js:121:27)
    at process.emit (events.js:210:5)
    at emit (internal/child_process.js:876:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
```
So how should I pass it to child_process? And how to set child process eviroment?

**Comment by josdejong** [comment]
If you have dependencies in your function, and it's not a standalone-function, you'll have to create a dedicated worker where you can load these dependencies.

Docs: https://github.com/josdejong/workerpool#dedicated-workers

**Comment by webbery** [comment]
I follow the guide.
`worker.js` like this:
```
workerpool.worker({
  getNouns: (str) => {
    console.info('----getNouns----')
    return NLP.retrieveNoun(str)
  }
})
```
`app.js` like this:
```
let algorithmpath = `./algorithm/NLP.js`
const cpus = require('os').cpus().length
const pool = workerpool.pool(algorithmpath, {minWokers: cpus > 4 ? 4 : cpus, workerType: 'process'})
image.tag = await pool.exec('getNouns', [fullpath])
```
Then I got this error:
```
Uncaught (in promise) Error: Workerpool Worker terminated Unexpectedly
    exitCode: `1`
    signalCode: `null`
    workerpool.script: `./algorithm/NLP.js`
    spawnArgs: `/Users/v_yuanwenbin/test/civet/node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Helper (Renderer).app/Contents/MacOS/Electron Helper (Renderer),./algorithm/NLP.js`
    spawnfile: `/Users/v_yuanwenbin/test/civet/node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Helper (Renderer).app/Contents/MacOS/Electron Helper (Renderer)`
    stdout: `null`
    stderr: `null`

    at ChildProcess.<anonymous> (/Users/v_yuanwenbin/…orkerHandler.js:282)
    at ChildProcess.emit (events.js:210)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:272)
```
Can I use relative path here? This is build by webpack.

**Comment by webbery** [comment]
> I follow the guide.
> `worker.js` like this:
> 
> ```
> workerpool.worker({
>   getNouns: (str) => {
>     console.info('----getNouns----')
>     return NLP.retrieveNoun(str)
>   }
> })
> ```
> 
> `app.js` like this:
> 
> ```
> let algorithmpath = `./algorithm/NLP.js`
> const cpus = require('os').cpus().length
> const pool = workerpool.pool(algorithmpath, {minWokers: cpus > 4 ? 4 : cpus, workerType: 'process'})
> image.tag = await pool.exec('getNouns', [fullpath])
> ```
> 
> Then I got this error:
> 
> ```
> Uncaught (in promise) Error: Workerpool Worker terminated Unexpectedly
>     exitCode: `1`
>     signalCode: `null`
>     workerpool.script: `./algorithm/NLP.js`
>     spawnArgs: `/Users/v_yuanwenbin/test/civet/node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Helper (Renderer).app/Contents/MacOS/Electron Helper (Renderer),./algorithm/NLP.js`
>     spawnfile: `/Users/v_yuanwenbin/test/civet/node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Helper (Renderer).app/Contents/MacOS/Electron Helper (Renderer)`
>     stdout: `null`
>     stderr: `null`
> 
>     at ChildProcess.<anonymous> (/Users/v_yuanwenbin/…orkerHandler.js:282)
>     at ChildProcess.emit (events.js:210)
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:272)
> ```
> 
> Can I use relative path here? This is build by webpack.

It seems that the '.' is pointed to the project directory. So I change it to correct position. Then everything is OK.
Thanks.

**Comment by josdejong** [comment]
Paths are indeed relative to the location of the script file (unless you use for example `__dirname`. Good to hear you have a working solution now 👍
