### ISSUE TITLE
Support for worker factory instead of script path

### ISSUE THREAD

**Issue by wh1t3cAt1k** [josdejong/workerpool#247]
Hi there!

My worker script is Typescript-only, compiled using `worker-loader` using a single rule:

```typescript
        rules: [
            {
                test: /function-worker\.ts$/,
                loader: 'worker-loader',
            },
            { ...
```

(all files are then compiled using `ts-loader`)

It is my impression though that with this library, I cannot specify the `.ts` extension as path to the script because it is being instantiated as `new Worker()` in the depths of `WorkerHandler`.

Without the pool, I currently export a custom constructor from my worker script:

```typescript
export default class FunctionWorker extends Worker {
    public constructor() {
        super('');
    }
}
```

and instantiate it call-site like that:

```typescript
import FunctionWorker from './function-worker';

const worker = new FunctionWorker();
```

which lets the webpack do its magic using `worker-loader`.

I would like to request a feature where you could pass a factory function like `() => new FunctionWorker()` to the pool constructor to avoid the necessity of pre-compiling the worker script to JS in a separate build step.

**Comment by josdejong** [comment]
Thanks for your suggestions. 

I'm not sure, but is what you mean what we've been discussing in #189? And maybe also #23 is part of the solution.
