### ISSUE TITLE
Environment file seems to be missing from recent release

### ISSUE THREAD

**Issue by mansona** [josdejong/workerpool#253]
I was getting the following error when running my app: 

```
(node:38338) UnhandledPromiseRejectionWarning: Error: Cannot find module './environment'
Require stack:
- /Users/mansona/git/opensource/empress/empress-documentation/node_modules/workerpool/src/index.js
```

Then I downgraded to `workerpool@6.1.0` and it started working again.

It seems like the last release has missed some of the required files 😬 looking at https://unpkg.com/browse/workerpool@6.1.1/src/ vs https://unpkg.com/browse/workerpool@6.1.0/src/ there is a significant difference

**Comment by rwjblue** [comment]
#243 leaves the package in a fundamentally broken state. The `main` entry point still points at `src/index.js` (and `npm publish` sees that this is your entry point and properly bundles it), but then any requires from that file do not work.

https://github.com/josdejong/workerpool/blob/0fb81b22b09d78eb14ce0053d0f428d6ac90cae0/package.json#L19

**Comment by josdejong** [comment]
Sorry guys, should be fixed now in `v6.1.2`. 

For reference, see #243.

**Comment by mansona** [comment]
Thanks a million @josdejong for getting this sorted 🎉

**Comment by josdejong** [comment]
Hm... well, I messed it up in the first place you know 😉

**Comment by josdejong** [comment]
yes true, thanks for your understanding 😄
