### ISSUE TITLE
Confused how to properly use timeout api

### ISSUE THREAD

**Issue by hhprogram** [josdejong/workerpool#254]
I'm trying to set a timeout for the worker threads. For context, I was just trying to make a toy example of some worker thread doing a CPU intensive task, and then setting up a timeout, so that the worker thread would throw an exception if it took longer than X.

I've done:

index.js
```
const workerpool = require('workerpool');
const pool = workerpool.pool(__dirname + '/workerPoolWorker.js');

pool.proxy()
.timeout(2000)
.then(worker => worker.doSomething())
.then(result => console.log(result))
.catch(err => console.log(err));
```

workerPoolWorker.js
```
const { promisify } = require('util');
const sleep = promisify(setTimeout);

const doSomething = async ()  => {
    await sleep(10000);
    return "shouldn't print";
}

workerpool.worker({doSomething: doSomething});
```

It doesn't seem to timeout properly, only when I put very small timeout values like 2, or 20 does it timeout. So, my thinking is that for some reason once my worker thread starts the `sleep` function the timeout is ignored? Or I'm not really sure what's happening here or what I'm doing wrong.

note: I tried moving the `timeout(2000)` method call around, as I thought maybe I had it in the wrong place in the promise chain, but that doesn't seem to have any impact.

Thanks!

**Comment by josdejong** [comment]
You're close 😄 . The timeout should be tight to an individual method call, like:

```js
pool.proxy()
  .then(worker => {
    worker.doSomething() 
      .timeout(2000)
      .then(result => console.log(result))
      .catch(err => console.log(err));
  })
```

or: 

```js
pool.exec('doSomething', [])
  .timeout(2000)
  .then(result => console.log(result))
  .catch(err => console.log(err));
```

**Comment by hhprogram** [comment]
ahh ok - that makes a lot of sense. Thanks for the prompt response!

**Comment by josdejong** [comment]
👍
