### ISSUE TITLE
Set memory limit for child_process

### ISSUE THREAD

**Issue by gauthier-th** [josdejong/workerpool#279]
Hello,
Is it possible to set a memory limit (with `--max-old-space-size`?) of a worker pool created with child_process?
Or a way to pass `--max-old-space-size` option to the child process?
Thanks

**Comment by josdejong** [comment]
Since `v4.0.0` the argument `--max-old-space-size` is passed to the child process ([see history](https://github.com/josdejong/workerpool/blob/master/HISTORY.md#2019-08-21-version-400)), is that what you mean?

**Comment by gauthier-th** [comment]
Kind of, but is there a way to specify a special value only for the child process?

**Comment by josdejong** [comment]
That is indeed an interesting idea. It's not possible right now but makes a lot of sense: create a set of workers with limited memory, differing from the memory set for the main process.

Anyone interested in implementing an option to configure the memory for the workers?

**Comment by gauthier-th** [comment]
I think I resolved this with the following:
```js
const workerpool = require('workerpool');
workerpool.pool(__dirname + '/myWorker.js', {
  workerType: 'process',
  forkOpts: {
    execArgv: ['--max-old-space-size=512']
  }
});
```

**Comment by josdejong** [comment]
Ah, that's a good idea 👍
