### ISSUE TITLE
Does node JS support?

### ISSUE THREAD

**Issue by junbao520** [josdejong/workerpool#305]
![image](https://user-images.githubusercontent.com/20721833/121659300-bf856500-cad4-11eb-9cc2-2a819c1c3c1b.png)
![image](https://user-images.githubusercontent.com/20721833/121659330-c6ac7300-cad4-11eb-878f-20831b57f0da.png)
When I try to use require in a function, I get an error

**Comment by josdejong** [comment]
From the docs https://github.com/josdejong/workerpool#offload-functions-dynamically:

> Note that both function and arguments must be static and stringifiable, as they need to be sent to the worker in a serialized form. In case of large functions or function arguments, the overhead of sending the data to the worker can be significant.

So if you need external libraries via require you'll have to use a dedicated worker instead: https://github.com/josdejong/workerpool#dedicated-workers
