### ISSUE TITLE
trying to multithread a project with multiple functions within it?

### ISSUE THREAD

**Issue by ryantupo** [josdejong/workerpool#307]
i have built a program that inside itself calls functions from multiple js files, and when i go to run it with 5 workers , it comes back undefined straight away following it through it stops at the point that a function is called i try to change my functions into promises but like do i need to do that for all the module functions aswel?? any help would be much appreciated im kinda new to node but need to get this working asap , really appreciate you making this ! insanely useful <3 thankyou to anyone who could help

**Comment by josdejong** [comment]
Inside workers you can use synchronous functions. Inside the main application you'll have to use promises (or `async`): results always come back async.

**Comment by ryantupo** [comment]
Okkkkk , I must be doing something wrong … thanks for the quick reply I’ll try and get it working today maybe there is something I’m missing.

**Comment by ryantupo** [comment]
Just out of interest what’s the case where a worker would come back as undefined ??

**Comment by josdejong** [comment]
I'm not sure what you mean

**Comment by ryantupo** [comment]
pool.exec('runScrape', ["acisco.com"])
    .then(function (result) {
      console.log('Result: ' + result); // outputs 55
    })
    .catch(function (err) {
      console.error(err);
    })
    .then(function () {
      pool.terminate(); // terminate all workers when done
    });


i run this code and i get Result: undefined being printed out

**Comment by ryantupo** [comment]
and inside the code i have it insert data into a mysql table and that isnt
happening

**Comment by josdejong** [comment]
I do not know what is inside your `runScrape`. Try work from one of the working examples provided in the library, and then step by step towards your application, to figure out why your function returns undefined.
