### ISSUE TITLE
Can someone create a v2 release branch

### ISSUE THREAD

**Issue by mansona** [josdejong/workerpool#308]
I've been tracking down an issue downstream caused by a problem with workerpool@2. @stefanpenner [mentioned that if I backported the fix we could release a patch version](https://github.com/babel/broccoli-babel-transpiler/pull/203#issuecomment-860796203) of v2 but I can't actually open the PR targeting the right place because there isn't currently a `v2` branch

Could someone create and push a `v2` branch targeting [this commit](https://github.com/josdejong/workerpool/commit/cfa5680426163e4119110d4bb9d35c99f822e708) and once that's done I can open a PR that implements the fix 👍

**Comment by josdejong** [comment]
Here you go: https://github.com/josdejong/workerpool/tree/v2

**Comment by josdejong** [comment]
> I believe the upgrade path is ideal, but adds some complexity in rollout/adoption/semver of the project in question.

Ah, I understand. Good to be careful with versioning.

**Comment by mansona** [comment]
Thanks everyone for the help! I have created the PR now https://github.com/josdejong/workerpool/pull/309 and I'm going to close this issue since we now have a v2 release branch 😂
