### ISSUE TITLE
gets stuck in infinite loop with .catch(function (err) {}

### ISSUE THREAD

**Issue by ryantupo** [josdejong/workerpool#311]
im running my multithreaded project and leave it running for 8 minutes , come back to it infinitely printing a undefinded err on the catch for the pool and it crashes , this was only 20% through the whole programs task any ideas? can share code if needed.

![image](https://user-images.githubusercontent.com/65490793/123418414-ee113e80-d5b0-11eb-955d-e0f6bed197fc.png)

**Comment by ryantupo** [comment]
it shows undefined 4 times each because i was printing errp[0] - err[4]

**Comment by ryantupo** [comment]
![image](https://user-images.githubusercontent.com/65490793/123420294-4e08e480-d5b3-11eb-99be-4bea2e07395a.png)
![image](https://user-images.githubusercontent.com/65490793/123420313-53662f00-d5b3-11eb-8bd6-bea472536e58.png)

the max pools is 12 so no idea why it didnt terminate the pool and keep going????

**Comment by ryantupo** [comment]
this keeps happening after running around 200-250 times

**Comment by ryantupo** [comment]
![image](https://user-images.githubusercontent.com/65490793/123481229-597ffe00-d5fb-11eb-87bd-6ad8b6363298.png)

**Comment by ryantupo** [comment]
found randomly a thread will max my cpu and do nothing

**Comment by ryantupo** [comment]
![image](https://user-images.githubusercontent.com/65490793/123481438-a06df380-d5fb-11eb-8db8-dc4c1c460b8a.png)
memory leak?

**Comment by josdejong** [comment]
It's hard to guess what's going on. How can I reproduce your issue?

**Comment by ryantupo** [comment]
using pool.exec calling a function , can that function loop and call
another function? over and over again? because when i try this it just ends
the program and does nothing.

[image: image.png]

sorry for repeatedly messaging asking questions but keep running into issues

**Comment by josdejong** [comment]
Well, yes, with any programming language you can create an infinite loop.

To figure out what's going on, try to strip away functionality until you figure out what's going wrong. Try to reduce your application to the simplest, most basic version until it works or you find the cause of the issue you're encountering. or start from a working example of workerpool, and build towards your application to figure out when things start to break.
