### ISSUE TITLE
Cannot find worker file after building electron app

### ISSUE THREAD

**Issue by rbuddy101** [josdejong/workerpool#312]
Hello,
I have an electron app that I'm using with workerpool, in my dev environment the worker pool is functioning flawlessly.
Once I build my app with electron builder, I'm receiving this error
`Error: Cannot find module 'C:\Users\wgrog\AppData\Local\Programs\nova\resources\app.asar\worker.js`

I have tried using "__dirname" in the `workerpool.pool()` and not using it with the same result.
Any guidance is appreciated.
Thanks!

**Comment by rbuddy101** [comment]
unpacking parts of the asar was a quick solution.

**Comment by josdejong** [comment]
👍

**Comment by serg06** [comment]
I'm running into the same issue, @rbuddy101 can you share more details of your fix?
