### ISSUE TITLE
Is it possible to persist heavy objects between calls ?

### ISSUE THREAD

**Issue by asafyish** [josdejong/workerpool#313]
I am trying to create a workerpool with a single function that has an object that is heavy to create, I would like to re-use that object instead of re-creating it over and over, is that possible ?

code example:
```js
import workerpool from 'workerpool';

function myFunc(param1, param2) {
   // I don't want to recreate this object over and over again, how can I reuse it ??
   const heavy = new HeavyObject(param1);
   // use heavy object
}

const pool = workerpool.pool({ minWorkers: 'max', workerType: 'thread' });

pool.exec(myFunc, [1, 2])
```

Does a dedicated worker can solve this efficiently ?

**Comment by josdejong** [comment]
Yes you can create a dedicated worker for that and do some one-time initialization there. If you configure say max 4 workers, for of these dedicated workers will be initialized and those are reused for all requests you do.

**Comment by asafyish** [comment]
Thanks. It's working.

**Comment by josdejong** [comment]
yay!
