### ISSUE TITLE
Kill a worker

### ISSUE THREAD

**Issue by asafyish** [josdejong/workerpool#314]
I have a worker and it got into a bad state, is it possible to signal from the worker to the pool, "kill me and recreate a new worker" ?

**Comment by josdejong** [comment]
Yes I think so, though you'll have to write a bit of plumbing yourself for this. When executing a method, you get back a promise. On this promise you can call `.setTimeout(...)` to automatically kill the worker when the request takes too long, and you can call `.cancel()` to kill the worker immediately. I think you could use Events ([see docs](https://github.com/josdejong/workerpool#events)) to send this bad-state signal to the main process, and then call `.cancel()` on this promise.
