### ISSUE TITLE
function exec can't load 3 parameters 

### ISSUE THREAD

**Issue by oasis1992** [josdejong/workerpool#315]
![image](https://user-images.githubusercontent.com/7834751/125214577-73694400-e27d-11eb-8a9b-5af5c0a57bd1.png)

**Comment by josdejong** [comment]
Looks like the type definitions `@types/workerpool` are not up to date. 

Anyone able to create a PR at DefinitelyTyped to update the definition of `exec`?

**Comment by tamuratak** [comment]
Done at DefinitelyTyped/DefinitelyTyped/pull/54584

**Comment by josdejong** [comment]
Thanks Takashi 👍
