### ISSUE TITLE
Electron use throw Error

### ISSUE THREAD

**Issue by yoonasy** [josdejong/workerpool#319]
```
    "electron": "6.1.12",
    "electron-download": "^4.1.1",
    "electron-log": "^4.3.5",
    "electron-updater": "^4.3.9",
    "vue-cli-plugin-electron-builder": "~1.4.6",

    "workerpool": "^6.1.5"
```

![image](https://user-images.githubusercontent.com/24489180/131701691-fc386c7a-4c5d-4e4a-99b7-197f406fafbc.png)

```
internal/worker.js:105 Uncaught (in promise) Error: The V8 platform used by this instance of Node does not support creating Workers
    at new Worker (internal/worker.js:105)
    at setupWorkerThreadWorker (workerpool.js:886)
    at setupWorker (workerpool.js:859)
    at new WorkerHandler (workerpool.js:976)
    at Pool._createWorkerHandler (workerpool.js:409)
    at Pool._getWorker (workerpool.js:286)
    at Pool._next (workerpool.js:232)
    at Pool.exec (workerpool.js:171)
    at Pool.exec (workerpool.js:176)
    at eval (index.js:551)
```

**Comment by yoonasy** [comment]
node: v12.21.0

npm: 7.21.1

**Comment by yoonasy** [comment]
```
const workerpool = require('workerpool');
const pool = workerpool.pool();

pool.exec(() => {}, []))
```
![image](https://user-images.githubusercontent.com/24489180/131703691-c3d48853-82a2-4502-aa55-896c4465053f.png)

Got an error

**Comment by josdejong** [comment]
You can try to configure `{ workerType: 'process' }` , looks like your version of nodejs doesn't support worker theads.

**Comment by yoonasy** [comment]
@josdejong  
Thank you for your answer, but it still doesn't work.
![image](https://user-images.githubusercontent.com/24489180/133031408-7cb0a7e4-8db1-4b31-91b7-438747af37ad.png)

**Comment by josdejong** [comment]
The option `workerType` needs to be passed when creating `pool` instead of when calling `pool.exec`, see docs: https://github.com/josdejong/workerpool#pool

**Comment by yoonasy** [comment]
@josdejong   Thank you very much.

![image](https://user-images.githubusercontent.com/24489180/133575278-efd02b78-48d1-442f-a585-09c026fde111.png)
