### ISSUE TITLE
how to use async function

### ISSUE THREAD

**Issue by SwapnilSoni1999** [josdejong/workerpool#328]
I have the following method 

**migrate.js**

```js
async function migrate (guildId) {
    const logger = new LogFile()
    let page = 1
    let migrateCount = 0
    const MAX = 50
    const query = { discord: { $exists: true } }
    const TOTAL = await User.countDocuments(query)
    logger.startProgress(TOTAL)

    while (page <= TOTAL) {
        const users = await User.find(query).skip((page - 1) * MAX).limit(MAX).select('discord')
        for (const user of users) {
            await discord.addMember({ userId: user.id, access_token: user.discord.access_token }, guildId)
            logger.updateProgress(`[${++migrateCount}/${TOTAL}] Users moved...`)
            await sleep(200)
        }
        page++
    }
    logger.log(`Finished.`)
}
```

It gets executed until first await statement comes. 

I have my app.js

**app.js**
```js
const migrate = require('./migrate-file')
const pool = workerpool.pool({ maxWorkers: 1 })

router.post('/some-path', (...) => {
   // code
   pool.exec(migrate, [guildId])
  /// more code...
})
```

**Comment by josdejong** [comment]
So what do you want me to do? 

The workerpool functions can be async, that's just fine. So I suppose there is some other bug or unexpected behavior in your code.

**Comment by cjativa** [comment]
@josdejong It does not look like functions prepended with `async` keyword work as expected.

This works as expected as a workerpool function

```js
function myFunction() {
  return new Promise(function (resolve) {
    setTimeout(function () {
      resolve(`Running some work`);
     }, 1000);
  });
}
```

But this does not 

```js
async function myFunction() {
  const theString = await new Promise(function (resolve) {
    setTimeout(function () {
      resolve(`Running some work`);
     }, 1000);
  });
  return theString;
}
```

**Comment by josdejong** [comment]
ah, good to hear 👍 . How did you find the issue? Did it properly throw an exception that can be caught with a regular `pool.exec(...).catch(err => ...)` ?

**Comment by SwapnilSoni1999** [comment]
yes got it thankyou <3

**Comment by cjativa** [comment]
> ah, good to hear 👍 . How did you find the issue? Did it properly throw an exception that can be caught with a regular `pool.exec(...).catch(err => ...)` ?

Yes exactly. The error had been caught with `.catch(...)` which I at first was not using.

Once I caught the error with that, I saw the error had been due to some TypeScript compilation issues (not sure exactly why, but I had to change my target compilation to like es2017 or higher).

**Comment by josdejong** [comment]
Thanks for sharing. I double checked, and as far as I can see everywhere in the docs and examples `.catch(...)` is used, I hope that helps people not forgetting to catch exceptions 😅 .

**Comment by stevebaxter** [comment]
I had this as well - the problem was using TS, I had to change `"target": "es6"` to `"target": "ES2017"` in tsconfig.json.
