### ISSUE TITLE
Workers termination

### ISSUE THREAD

**Issue by raf555** [josdejong/workerpool#330]
Hi, 

I just want to make sure about the workers termination. 
Do they terminate themselves when they are done with the task?
Or should I include pool.terminate() all the time?

Thank you.

**Comment by raf555** [comment]
Nevermind, I figured out they never terminate themselves.

**Comment by josdejong** [comment]
That is correct, they don't terminate themselves. 

As long as you need the workers it is most efficient to keep them alive: spinning up a worker takes time. If you are really done, you can terminate the workerpool to free memory.
