### ISSUE TITLE
TypeError: Cannot set properties of null (setting 'killed')

### ISSUE THREAD

**Issue by HMilbradt** [josdejong/workerpool#332]
Seeing this error when doing a bit of stress testing.  The server has a single worker managed by this library.

For context, the jobs I submit are cancellable.  This error only happens when I call `promise.cancel()`.  My guess is that it's related to attempting to cancel an already completed or cancelled job.

Raw logs from my server:

2022-01-12T12:00:04.065-08:00 | /usr/src/app/node_modules/workerpool/src/WorkerHandler.js:433
-- | --
  | 2022-01-12T12:00:04.065-08:00 | me.worker.killed = true;
  | 2022-01-12T12:00:04.065-08:00 | ^
  | 2022-01-12T12:00:04.065-08:00 | TypeError: Cannot set properties of null (setting 'killed')
  | 2022-01-12T12:00:04.065-08:00Copy    at ChildProcess.<anonymous> (/usr/src/app/node_modules/workerpool/src/WorkerHandler.js:433:30) | at ChildProcess.<anonymous> (/usr/src/app/node_modules/workerpool/src/WorkerHandler.js:433:30)
  | 2022-01-12T12:00:04.065-08:00 | at Object.onceWrapper (node:events:510:26)
  | 2022-01-12T12:00:04.065-08:00 | at ChildProcess.emit (node:events:402:35)
  | 2022-01-12T12:00:04.065-08:00 | at ChildProcess.emit (node:domain:475:12)
  | 2022-01-12T12:00:04.065-08:00 | at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)

**Comment by josdejong** [comment]
Thanks for your report. How can I reproduce this issue?
