### ISSUE TITLE
pass worker_data when workerType is thread

### ISSUE THREAD

**Issue by EngHosam** [josdejong/workerpool#333]
I need to pass worker_data when workerType is thread

**Comment by josdejong** [comment]
Would the brand new option `onCreateWorker` help? If not can you elaborate?

**Comment by EngHosam** [comment]
no, I need to add option while call ( worker.pool(script,options) )

**Comment by josdejong** [comment]
I don't understand what you mean. You'll have to elaborate.

**Comment by EngHosam** [comment]
when create new pool 
by:
`worker.pool(script_path,options)`
i need to set worker_data on options
because read it on worker script

**Comment by josdejong** [comment]
You can use `onCreateWorker` to pass dynamic or static data to a specific worker when the worker is being created

**Comment by EngHosam** [comment]
ok, I am cannot see onCreateWorker  because I am use `@types/workerpool`

please are you know why [ `@types/workerpool` ] not up to date with workerpool library ?!!

**Comment by josdejong** [comment]
Ahh, good point. These functions where published yesterday and the type definitions are indeed not updated.

I opened a separate issue to address this: https://github.com/josdejong/workerpool/issues/334 (help is welcome)

Until then you can define the functions yourself of course or use `@ts-ignore` or so.

**Comment by EngHosam** [comment]
thank you @josdejong
