### ISSUE TITLE
Move typescript definitions of @types/workerpool into the library and bring the definitions up to date

### ISSUE THREAD

**Issue by josdejong** [josdejong/workerpool#334]
Having the type definitions in the repo itself will make it easier to keep the definitions on par with the API.

Anyone able to help out here?

**Comment by 1valdis** [comment]
I can try this. What would be the plan here? Do I just make a merge request with `index.d.ts` (with corrections if necessary)?

**Comment by josdejong** [comment]
Thanks Vladyslav, that would be great!

I expect what we need is:

- a file `types/index.d.ts` containing the types to be published
- a file `test/types/index.ts` to test the types and verify that they all work, and a script which runs the file

If you have thoughts or ideas I would love to hear them.

**Comment by 1valdis** [comment]
Do you want the script to be run from terminal, like `npm run test-types`?

**Comment by 1valdis** [comment]
I see that on #54 you suggested a move to Typescipt. If the library is moved to Typescript then there would be no need in writing index.d.ts by hand and maintaining it. Are you still considering the move?

**Comment by josdejong** [comment]
Yes definitely, I would like to move `workerpool` to TypeScript and ES modules. I haven't found time for that refactoring so far.

**Comment by 1valdis** [comment]
I can consider refactoring to TypeScript that would compile to ES Modules. Some packages are dropping CommonJS support completely at this point, for example `file-type@16` and up only works in ES Modules. Would you consider that as well?

**Comment by 1valdis** [comment]
I'm asking about dropping CommonJS because I haven't had experience with publishing both CommonJS and ES Modules builds. However judging by the available resources, that can be made quite straightforwardly as well, so there may be no need in dropping CommonJS :)

**Comment by josdejong** [comment]
> I can consider refactoring to TypeScript that would compile to ES Modules

wow that would be awesome! Please be aware that this will really cost some time. There are for example some specific scripts to generate an embedded worker, that may complicate things.

At this point I think the library should generate&publish both ESM and UMD (currently, only UMD is published), and ideally the npm package should stay backward compatible. It requires some work to set up a build script for that, but that ensures a smooth transition. Does that make sense? 

I do have experience with such a setup: I recently did that for https://github.com/josdejong/lossless-json. Maybe that setup can be of help.

**Comment by 1valdis** [comment]
> Does that make sense?

It sure does. I'm looking at what realistically needs to be supported, or if not then what can be cleaned up as not needed anymore.

For example, what's the ES version requirement? Do we want to still compile to ES5? Otherwise I think there's no need for, for example, Promise polyfill? What's the choice between "we need to keep backwards compatibility at all cost" and "whoever needs to run this thing on IE10 can just keep using `workerpool@6` or lower"?

I don't see `engines` section in package.json. What is the minimum Node.js version for this to run? Oldest LTS at the moment is 14. If we take it as a minimum, do we need to keep `child_process` option considering that `worker_threads` is available in all versions at this point?

Do you want to keep gulp here? In `loseless-json` I only see rollup, however there's nothing like `embeddedWorker` generation.

**Comment by josdejong** [comment]
Good point. With backward compatible I mostly meant that when I use `workerpool` in some up-do-date project, and upgrade to the next version of `workerpool`, then ideally everything should just keep working. We should definitely keep support for `child_process`. To minimize the amount of moving parts, I think it would be good to limit this refactor to syntactic changes in the code (from CommonJS to ESM, and add types), and not make functional changes.

- I think we should drop support for IE11 and older (has reached EOF)
- We should support node.js 14 and newer (12 has reached EOF)

I think we should get rid of `gulp` since it is not maintained anymore. rollup can do the building indeed, and we can move code for `embeddedWorker` in a regular node.js script.

**Comment by 1valdis** [comment]
Sounds good. Back to the Promise polyfill, do we keep it or not? Since we won't compile to ES5, then the next is ES6 and Promises are a feature of ES6, so should be safe to use native Promises?

**Comment by 1valdis** [comment]
There are a couple other issues.
1. `npm run coverage` doesn't work for me on Windows. There's an issue with the command itself that it contains newlines, but fixing that gives
```
No coverage information was collected, exit without writing coverage information
workerpool\node_modules\.bin\_mocha.CMD:1
@ECHO off
^

SyntaxError: Invalid or unexpected token
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1032:15)
    at Module._compile (node:internal/modules/cjs/loader:1067:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Object.Module._extensions.<computed> [as .js] (workerpool\node_modules\istanbul\lib\hook.js:109:37)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at runFn (C:\Users\Valdis\workerpool\node_modules\istanbul\lib\command\common\run-with-cover.js:122:16)
    at C:\Users\Valdis\workerpool\node_modules\istanbul\lib\command\common\run-with-cover.js:251:17
```
2. `examples/embeddedWorker` when doing everything as Readme in that folder says, the example also doesn't seem to work. Opening app.html shows plain white page. Console shows `GET file://.../workerpool/examples/embeddedWorker/dist/app.bundle.js net::ERR_FILE_NOT_FOUND`

**Comment by josdejong** [comment]
> Sounds good. Back to the Promise polyfill, do we keep it or not? Since we won't compile to ES5, then the next is ES6 and Promises are a feature of ES6, so should be safe to use native Promises?

The [Promise](https://github.com/josdejong/workerpool/blob/master/src/Promise.js) class of `workerpool` is not a regular polyfill, but comes with the ability to cancel and timeout a promise. We should keep it, at least during this refactor. If needed, we could start a separate discussion to see if we can improve on that, utilizing the built-in `Promise` class some way.

About code coverage: good point. I opened a separate issue for it: #360

About the embedded example: I just tested (also on Windows), and the example works on my machine (npm install, npm run build, then open app.html). The dependencies of the example should be updated though. Can you open a separate issue to discuss the issue you're encountering?

**Comment by iSuslov** [comment]
Hey guys, did you come up with a solution for this?

PS: I have a chance to say thank you @josdejong for this library! I was amazed by performance tests that I did recently, don't know how, but for Fibonacci sequence algorithm it beats `main thread` and `comlink` package, being nearly 30% faster. After being impressed once, I decided to take a closer look at the codebase and was impressed again by the clarity of your code. Long story short, I'm now wondering if we can move this lib to typescript which could reduce its bundle size depending on compile target.    

Let me know if you need help!

**Comment by iSuslov** [comment]
@josdejong sorry for confusion here, actually I meant moving to Typescript.

**Comment by josdejong** [comment]
Ah, clear. 

@Michsior14 told two weeks ago that he's working on a full TS migration but I'm not sure what the status is, see https://github.com/josdejong/workerpool/issues/381#issuecomment-1458952331. @Michsior14 any update on that?

**Comment by Michsior14** [comment]
Not really, didn't have much time to continue. I will try to do something about it in the next days.

**Comment by josdejong** [comment]
👍 if you don't have time or it doesn't work out just let me know, then maybe someone else can pick it up.

**Comment by Michsior14** [comment]
Unfortunately I don't know yet when I will have time to finish this up. If someone want's to follow (https://github.com/Michsior14/workerpool/tree/feat/ts-migration) or start from scratch please feel free to do so.

**Comment by josdejong** [comment]
Thanks for giving it a go @Michsior14 and for getting back, no problem at all.

Anyone else able to pick this up? (either a full TypeScript rewrite, or, as a first step, just move the TS definitions inside the repository).

**Comment by iSuslov** [comment]
Hey @josdejong, I would like to give it a try. 
There was already a brief discussion on how ideally typescript rewrite should look like. I think I will come up with a draft PR where we can continue this discussion but in "code review" format.

**Comment by josdejong** [comment]
Thanks Ivan! Sounds good
