### ISSUE TITLE
Task's error is being resolved

### ISSUE THREAD

**Issue by danielfluk** [josdejong/workerpool#336]
I have a proxy for a workerpool which has some async tasks.
Some of the async tasks include `try`  and `catch` blocks.

I want to return an error from the `catch` block so I return `new Error`.

```typescript
proxy.someFailedAsyncTask()
.catch(err => console.error(`Error`))
.then(res => console.log(`Success`))
```
Excpected behaviour:
output: error

Actual behavior:
output: Success

**Comment by josdejong** [comment]
Can you share a full example on how to reproduce your issue?

**Comment by danielfluk** [comment]
Hi, sorry for the delay, I've been quite busy at work.
Here is the code for reproducing:

Worker:
```typescript
const someFailedAsyncTask = async () =>
  new Promise((resolve, reject) => {
    setTimeout(() => reject(new Error('Task failed')), 1000);
  });

workerpool.worker({
  someFailedAsyncTask,
});
```

Controller:
```typescript
import * as path from 'path';
import * as workerpool from 'workerpool';

type ScannerWorker = {
  someFailedAsyncTask: () => string;
};

class WorkerpoolController {
  private workerpool: workerpool.WorkerPool;
  pool: workerpool.Proxy<ScannerWorker>;

  async init() {
    this.workerpool = workerpool.pool(
      path.join(__dirname, 'worker.js')
    );
    this.pool = await this.workerpool.proxy();
  }

  stats() {
    return this.workerpool.stats();
  }
}

export default new WorkerpoolController();
```

Calling the task:
```typescript
(async () => {
  await workpoolController.init();
  workpoolController.pool
    .someFailedAsyncTask()
    .catch((err) => console.log('task failed'))
    .then((res) => console.log('task succeed'));
})();
```

**Comment by josdejong** [comment]
Thanks for putting together this example. When I run this, I get the following output (after 1 second):

```
task failed
task succeed
```

Which is exactly what I would expect: the method throws after 1 second, then you `catch` the exception, after that the promise chain continues, and you have a `then` case printing `task succeed` (it will _always_ print that: any exception is caught right before it). I guess you want to switch that, and first run the `then` and after that run `catch`, so `task succeed` is only printed when there was no exception:

```js
  workpoolController.pool
    .someFailedAsyncTask()
    .then((res) => console.log('task succeed'))
    .catch((err) => console.log('task failed'))
```
