### ISSUE TITLE
Working with typescript causing an error: The worker script extension must be \".js\", \".mjs\", or \".cjs\". Received \".ts\"

### ISSUE THREAD

**Issue by PrabhuPuredla95** [josdejong/workerpool#345]
var workerpool = require('workerpool')
var pool = workerpool.pool(__dirname + '/../workers/bulk_operations.ts') //causing the error

I have installed this module as well: https://www.npmjs.com/package/@types/workerpool

**Comment by PrabhuPuredla95** [comment]
Node version: v14.19.0
typescript: v4.4.3

**Comment by josdejong** [comment]
You'll first need to create a bundle of your `bulk_operations.ts` file, and then load that bundle as worker.

See also #189

**Comment by PrabhuPuredla95** [comment]
Thank you. Will try and let you know
