### ISSUE TITLE
How to pass a callback function to `onCreateWorker` method?

### ISSUE THREAD

**Issue by PratikDarak** [josdejong/workerpool#349]
Hi,

I am working on a scenario where I want to execute a callback function each time a new worker is created. Can you please share an example of how it can be achieved?

To give a context in little more detail, I am using Go + WASM + Workerpool setup where I am offloading the WASM tasks to workerpool so that it doesn't occupy my main thread. In this setup, I want to execute `go.run` command with the WASM instance in each worker so that each worker can execute the WASM functions.

It will be really helpful if you can share an example of how can I pass the callback function to `onCreateWorker` method. Thank you.

**Comment by josdejong** [comment]
Maybe the following example in the unit tests helps: 

https://github.com/josdejong/workerpool/blob/143b89b6909b07b8cdf72fe5813f96b3e6d38b5c/test/Pool.test.js#L100-L134

**Comment by PratikDarak** [comment]
Hi @josdejong , I saw this example but here we are modifying the options. I need something like this:

```
const pool = workerpool.pool(WASM_WORKER_FILE, { 
	minWorkers: 2,
	maxWorkers: 5,
	workerType: "web",
	onCreateWorker: () => {
		// Set of steps I want to execute
		...
	}
});
```

Is this possible with current release?

**Comment by josdejong** [comment]
So what does "Set of steps I want to execute" do? is it some actions on the side of the worker or the main thread?

**Comment by PratikDarak** [comment]
yes.. I want to instantiate a go instance once the worker is started.
For example, I want to run this command: `go.run(instance)` if a new worker is created

**Comment by josdejong** [comment]
If you have a dedicated worker script, you can simply run any code whenever the code is loaded. If you put `console.log('hello world')` on the first line in the file it will output this text in the console when a worker is loaded. You do not need `onCreateWorker` (which is executed in the main thread right before a worker is created) for that. It may be that you need a specific identifier or so to keep workers apart, and that is what you can pass via `onCreateWorker`.

**Comment by PratikDarak** [comment]
Got it. I will try it out. Thanks @josdejong 👍 .

**Comment by PratikDarak** [comment]
@josdejong : Just 1 more clarification I need. When using the dynamic web worker setup, once a worker is spawned, does it stay alive till the lifecycle of the application? Or does it gets terminated once the task is done and then gets respawned once the new tasks are added?

**Comment by josdejong** [comment]
👍 

> When using the dynamic web worker setup, once a worker is spawned, does it stay alive till the lifecycle of the application?

The worker stays alive until you terminate the workerpool, or when it crashes. If you want to monitor what's going on with your workers you can use the functions `onCreateWorker`, `onTerminateWorker`, and `stats` to keep track.
