### ISSUE TITLE
Allow main thread to cleanly cancel workers

### ISSUE THREAD

**Issue by tahini** [josdejong/workerpool#353]
The `cancel` method of the worker promise sends a signal that kills the worker thread entirely, leaving any resources used in the thread in a state of dismay. 

For example, my worker starts processes of its own and use and produces output files, etc. If this task should be cancelled, I would like my worker to properly terminate those processes and make sure the files are in a usable state (close json objects, etc). Now, if the worker task is canceled, all those resources are left as they last were and pollute the system.

Is it possible to send a softer cancel signal to the worker instead of the current kill? Or is there any mechanism by which the main thread could send some message that the worker can listen to and avoid using that cancel signal?

**Comment by josdejong** [comment]
Thanks, that is an interesting case indeed. 

I suppose `onTerminateWorker` is not usable in this case because that is executed in the main thread?

**Comment by adityapatadia** [comment]
Yes, I also open file streams in worker threads. Worker thread does not know when it's going to be cancelled so closing those writable streams is not possible. If main thread can pass some message to workers, they can complete their work and then exit on their own.

**Comment by josdejong** [comment]
Yes, makes sense.

Right now, the workerpool calls the `.kill()` method on the child_processes / thread / worker. I'm not sure if there isn't an event fired for that in the worker, that can be used to detect being killed and gracefully close resources?

Anyone able to help think through and implement a solution for this?

**Comment by josdejong** [comment]
A new option `onTerminate` is now available on the worker side in `v6.4.0`
