### ISSUE TITLE
support worker execArgv

### ISSUE THREAD

**Issue by MrPupik** [josdejong/workerpool#356]
I'm using `workerpool` in nodejs with `worker_threads`. I've noticed that threads does not throw errors.
after some digging I noticed that my thread is running async function and that he default thread behavior for UnhandledPromiseRejection is not to exit.

to support this, `worker_thread` has `execArgv` parameter:
`const worker = new Worker(__filename, {
  execArgv: [...process.execArgv, '--unhandled-rejections=strict' ]
})`

[see full discussion here](https://github.com/nodejs/node/issues/33834)

Could you support such option somehow? currently I'm implementing specific `handleThreadError` function for this

**Comment by josdejong** [comment]
Ah, good point. So, the library does have support for passing options like `execArgv` to `child_process`: `forkArgs` and `forkOpts`, but something similar for the `execArgv` of `worker_thread` is missing, right? Makes sense to add support for that.

Anyone interested in working this out in a PR? Help would be welcome.

**Comment by josdejong** [comment]
This is addressed now in `v6.3.0` thanks to #357
