### ISSUE TITLE
Node just got worker_threads

### ISSUE THREAD

**Issue by stefanpenner** [josdejong/workerpool#38]
Hey, we have been using workerpool for some time to help parallelize ember-cli builds. Thanks for a great project!

Anyways, I wanted to share that node just added experimental support for worker_threads: https://github.com/nodejs/node/pull/20876 And this most likely could be of benefit to this project.

I'll likely kick the tires a bit, if it turns out good would their be interest in a PR providing support for those who opt-in?

**Comment by josdejong** [comment]
Thanks @stefanpenner, worker_threads sounds really nice, I hadn't really looked in it so far. It should be relatively straight forward to implement support for it in `workerpool` since the API of worker_threads is very similar to that of browser web workers, I hope it will work out nicely.

A PR would be very welcome!

**Comment by shusson** [comment]
If someone does take a look at this, just a heads up on this warning from the [worker.terminate](https://nodejs.org/api/worker_threads.html#worker_threads_worker_terminate_callback) doc

> Warning: Currently, not all code in the internals of Node.js is prepared to expect termination at arbitrary points in time and may crash if it encounters that condition. Consequently, you should currently only call .terminate() if it is known that the Worker thread is not accessing Node.js core modules other than what is exposed in the worker module.

**Comment by rwjblue** [comment]
Node 11.7.0 was recently released which enables workers by default (removing the `--experimental-worker` flag).

https://nodejs.org/en/blog/release/v11.7.0/

**Comment by josdejong** [comment]
Yes indeed, awesome!

I would love to add support for nodejs threads, but on short term I'm in lack of time. Any help would be very welcome!

**Comment by stefanpenner** [comment]
Thanks for the bump, I'm going to try and carve out some time today.
