### ISSUE TITLE
Update type definitions with the new 'Transfer' options

### ISSUE THREAD

**Issue by Fzlw** [josdejong/workerpool#381]
Hello, dear author. I have a problem with TypeScript, Can you update @types/workerpool on Transfer support

**Comment by josdejong** [comment]
Thanks for reporting.

Anyone able to create a PR to update the type definitions at definitely typed, or move them inside the library? Help would be welcome.

**Comment by Michsior14** [comment]
Types updated at definitely typed (https://github.com/DefinitelyTyped/DefinitelyTyped/pull/64339), additionally I am playing around with full TS migration for the project, but haven't time to finish it yet.

**Comment by josdejong** [comment]
Thanks a lot Michał.

> I am playing around with full TS migration for the project, but haven't time to finish it yet.

That sounds really promising, good to know!
