### ISSUE TITLE
Send message to persistent worker's stdin

### ISSUE THREAD

**Issue by MarkWasfy00** [josdejong/workerpool#382]
I want the user to send inputs to the stdin in workerpool 
How can I achieve that?

**Comment by josdejong** [comment]
Can you explain in more detail?

**Comment by MarkWasfy00** [comment]
Is workerpool capable of keeping the spawn function alive and can the user send input to stdin?

**Comment by josdejong** [comment]
The user can enter inputs in the main process. From the main process you can execute a function in a worker, so you can send information to the worker. However if you have configured multiple workers, you cannot know which of the workers will receive the message, the workers are anonymous.

**Comment by MarkWasfy00** [comment]
will it be supported in the future or is not compatible with the current lib main idea?
It will be useful  to manage persistent concurrent workers that have the ability to make users send inputs to the stdin 
anyways thank you for your answer

**Comment by josdejong** [comment]
I'm still not sure what you mean. What do you mean with "send inputs to the stdin"?

**Comment by MarkWasfy00** [comment]
I'm currently working on an online compiler 
When the user uses my site he can run for example python script that has this code 
```
x = input("Enter your name: ")
print(f"your name is {x}")
```
and when the user hits run it will wait for the user to send his input back to the script 
in the meanwhile, the site can hold a lot of users which is not possible for the server to handle, your library comes in handy and can manage the workers but I can't send back to the worker the user input which he will provide
