### ISSUE TITLE
how to use FileReaderSync in workerpool

### ISSUE THREAD

**Issue by Ljy66** [josdejong/workerpool#393]
Hello！Recently I wanted to use workerpool to parse uploaded large files.  Do you have an example to refer to if possible? Thank you！

**Comment by josdejong** [comment]
There is no example of that. Feel free to share an example here when you've implemented this, that may help others 😄.

Basically: you'll have to run `FileReaderSync` in the main thread, send the loaded text data to a worker, and do your parsing step there.

**Comment by Ljy66** [comment]
Ok, I will try it myself. Thank you for your reply
