### ISSUE TITLE
MongooDB  instance is not connecting in dedicated worker 

### ISSUE THREAD

**Issue by striveminzkishan** [josdejong/workerpool#404]
we are using dedicated workers and in our worker code we are executing MongoDB query but we are getting timeout error from the MongoDB server , but the same query works outside of the worker.

our query 
`let queryOutput = await dbModel.findOne({ _id: 1})`

getting error 

` MongooseError: Operation `dbModel.findOne()` buffering timed out after 10000ms`

**Comment by josdejong** [comment]
I'm not sure how I can help. I did some googling on using MongoDB in a worker thread, maybe you're hitting the following issue:

https://stackoverflow.com/questions/65746964/how-to-insert-a-new-data-in-mongodb-using-worker-thread-in-nodejs

**Comment by striveminzkishan** [comment]
after using this getting error 
 Cannot overwrite `my model name ` model once compiled.\n    at Mongoose.model 
 
 as we have already that model in my code 
 
 we need to import that into worker file

**Comment by josdejong** [comment]
Then you need to import your model in both your main application and in a dedicated worker.

**Comment by striveminzkishan** [comment]
Hello @josdejong i have done this 

![image](https://github.com/josdejong/workerpool/assets/93194016/8ebe334c-51d7-46c2-b163-382221e20175)

please check in the image 

but getting issue 

we are using dedicated workers and in our worker code we are executing MongoDB query but we are getting timeout error from the MongoDB server , but the same query works outside of the worker.

our query
let queryOutput = await dbModel.findOne({ _id: 1})

getting error

MongooseError: OperationdbModel.findOne() buffering timed out after 10000ms

**Comment by josdejong** [comment]
Ok so loading the code in the worker works, but running a mongo query not.

I think you'll have to do more debugging and googling. As a first step I would try to create a minimal demo for yourself where you can rule out as much causes as possible. For example rule out `workerpool` by creating a thread yourself and running the mongo query there (I don't expect the issue has to do with `workerpool`, but you never know).

**Comment by striveminzkishan** [comment]
HI @josdejong 

I am still struggling with this problem could you please help with the demo code 

Thanks

**Comment by josdejong** [comment]
To debug your issue, you'll have to rule out possible causes of the issue until you find the root of the issue. Possible causes: there is something wrong with MongoDB, there is something wrong with Mongoose, there is something wrong with workerpool, there is something wrong with running MongoDB in a worker thread, there is something wrong with your local environment, and maybe some more. 

Sometimes it is easiest to start with a minimal piece of code that works (i.e. a minimal connection to MongoDB that executes a `findOne`, and then step by step add all the components that you're using (move it into a worker thread, add mongoose, add workerpool), working towards your full application. 

Or the other way around: sometimes it is easiest to take your broken application, and start stripping code and components until it works.

**Comment by striveminzkishan** [comment]
Hello @josdejong  

yes i have checked with a minimal piece of code that works  without the MongoDB model 

getting the same issue when we use the MongoDB model it is working fine 

MongooseError: OperationdbModel.findOne() buffering timed out after 10000ms

**Comment by striveminzkishan** [comment]
Hello @josdejong 

when i run worker without MongoDB model the it is working ,
means if i did not import any MongoDB  model and just perform only some calculation then it is working fine 


we are getting issue only when we try to find any record with mongoDB 


Thanks

**Comment by josdejong** [comment]
Good to hear you're one step further. I'm not entirely sure what your findings mean. Please let me know if it turns out to be some issue with `workerpool` that we can fix or improve upon. If it is not related to `workerpool` let's close this issue OK?
