### ISSUE TITLE
terminate(true) didn't kill the pool process

### ISSUE THREAD

**Issue by mostafa-hisham** [josdejong/workerpool#418]
using this example
```
        let result = null;
        try {
             result = await pool.exec('doTheWork', [job]).timeout(5000);
        }catch (err){
            console.log(err);
            result = {
                code:500,
                ...err
            }
        }
        await pool.terminate(true);
        return result;
```
on catching a timeout error
terminate(true) didn't kill the pool process
and this 
`result = await pool.exec('doTheWork', [job]).timeout(5000);`
didn't kill the process too

`doTheWork` function has an infinite loop
```
        while (true){
            console.log(new Date().getTime());
        }
```

**Comment by josdejong** [comment]
Thanks for reporting. I tried to reproduce what you describe but without success. Can you work out a complete example demonstrating the issue?

**Comment by josdejong** [comment]
@mostafa-hisham how can we reproduce your issue exactly?

**Comment by josdejong** [comment]
Closing this issue due to a lack of response.
