### ISSUE TITLE
capture stdio during execution of a task

### ISSUE THREAD

**Issue by cpendery** [josdejong/workerpool#423]
Would it be possible to have an API exposed where after the completion of a task, I receive any stdout or stderr that occurred during the task? I don't want to use `forkOpts.stdio` with `inherit` since I need to suppress / refine the task's output. It would be great to expose child/thread's stdout/stderr since there isn't support in [NodeJS](https://github.com/nodejs/node/issues/8033) to capture it within the worker.

**Comment by josdejong** [comment]
I guess `forkOpts.stdio` (for child processes) or `workerOpts` (for worker threads) is the only option.

**Comment by josdejong** [comment]
Published now in `v9.1.0`, see #425.
