### ISSUE TITLE
What should I do to solve the error I introduced into the vue project? Do I need to configure something in webpack

### ISSUE THREAD

**Issue by wangyiyou** [josdejong/workerpool#430]
![1708504543716](https://github.com/josdejong/workerpool/assets/65714790/2e10176a-0b0e-472b-a619-239e37191fcf)

**Comment by josdejong** [comment]
The package is a CommonJS / UMD build, maybe that requires some configuration in your ESM setup?

How can we reproduce your issue?

**Comment by josdejong** [comment]
I had a closer look at the error message, it says "Module parse failed: unexpected token (509:30)" in the file `workerpool/dist/workerpool.js`. At that position in the code, [optional chaining](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining) `?.`  is used. So, this is not an issue with ESM/CommonJS, but a relatively new JavaScript operator that is not understood by your setup. The optional chaining operator was introduced 4 years ago. I guess that you have to update your Webpack setup to support the latest JavaScript features.

**Comment by josdejong** [comment]
Closing due to a lack of response. Please reopen if needed.
