### ISSUE TITLE
Worker thread crashed silently or killed by OS while pool.stats considers it as active task

### ISSUE THREAD

**Issue by itsdheerajbudhiraja** [josdejong/workerpool#431]
I am using workerpool to validate a large amount of data (around 20k records array). After validating each record, there is a database call for each record also inside the worker code

After processing a few records, Logs from worker thread stops printing and also CPU usage goes down indicating worker thread has crashed. I also have setInterval method in the main thread which prints Pool stats and it is printing active thread as 1.

In logs I don't see any std err from the worker thread.

How can I determine the root cause for this?

Is there any process.on("error" | "sigterm" | "sigkill") method I can pass to the worker thread to handle OS signals if the OS is terminating that thread abruptly?

**Comment by josdejong** [comment]
Some ideas for debugging:

- Run the process in the main thread instead to see if/how it crashes, maybe that gives more information
- Add a try/catch block around the process to see if it throws some exception
- Monitor the memory usage of the process when running, see if it goes out of memory
- Run your node.js application with a debugger attached
