### ISSUE TITLE
Error when testing in react component

### ISSUE THREAD

**Issue by theahmadjawad** [josdejong/workerpool#435]
I am having trouble testing a component that uses workerpool. I am getting the following error
`TypeError: 'postMessage' requires 2 arguments: 'message' and 'targetOrigin'`

I am using vitest. This Is my vitest config
  ```
test: {
    globals: true,
    environment: 'jsdom',
    setupFiles: ['@vitest/web-worker'],
  },
```

This is how I am using the workerpool inside the component
 ```
const pool = useMemo(() => workerpool.pool(Worker, {
    workerOpts: {
      type: 'module',
    },
    workerType: 'web',
  }), []);
```

**Comment by josdejong** [comment]
Closing due to lack of response. Please reopen if needed.

**Comment by PratikDarak** [comment]
Hi @josdejong , I am also facing this same exact issue in my project where we are using "vitest" to test out the workerpool.

Vitest config:
```
test: {
	globals: true,
	include: ["**/*.spec.ts"],
	environment: "jsdom",
	setupFiles: ["@vitest/web-worker"],
	silent: true
},
```

Workerpool creation:
```
// Create pool of workers for "wasm_worker" script
export const wasmWorkerPool = workerpool.pool(WasmWorkerURL, {
	minWorkers: "max",
	maxWorkers: optimum_wasm_workers,
	workerType: "web",
	workerOpts: { type: import.meta.env.PROD ? undefined : "module" }
});

// Create pool of workers for "api_worker" script
export const apiWorkerPool = workerpool.pool(APIWorkerURL, {
	minWorkers: "max",
	maxWorkers: optimum_api_workers,
	workerType: "web",
	workerOpts: { type: import.meta.env.PROD ? undefined : "module" }
});
```

Unfortunately I am not sure how to reproduct this but it is only happening while running the test pipeline in CI-CD.

@theahmadjawad : Were you able to solve this issue?
