### ISSUE TITLE
Webworker implementation does not handle on message callbacks.

### ISSUE THREAD

**Issue by t0oF-azpn** [josdejong/workerpool#438]
I tried to reproduce the example of sending back data from the worker to the pool (from the doc https://github.com/josdejong/workerpool#events), in a browser environment (ie. with web workers):

https://codesandbox.io/p/sandbox/workerpool-in-a-react-project-forked-dgjxxc

The example demonstrates 2 issues:
- `pool.exec("someFunctionName")` does fail in a browser environment 
- `pool.exec(someFunction)` does perform the computation but fails to send the web-worker message to the pool.

**Comment by josdejong** [comment]
Thanks for reporting and implementing a fix in #439.

**Comment by josdejong** [comment]
Fixed in `v9.1.1`
