### ISSUE TITLE
demo run throw  Error: Cannot find module '...\out\main\worker.js'   after  vite build

### ISSUE THREAD

**Issue by whaleluo** [josdejong/workerpool#459]
```js
 const pool = workerpool.pool();
  pool.exec(fibonacci,[100]).then(res=>{
      console.log('result:',res)
  }).catch(error => {
      console.log('result:',error)
  })
```

I found worker.js at  npm_modules/worker_pool/dist , so  vite  that  source code not use ' work.js' , that no bundle it

**Comment by josdejong** [comment]
Thanks for reporting. How can I reproduce your issue exactly? Can you create a minimal demo?

**Comment by josdejong** [comment]
Closing due to a lack of response. Please reopen if this is still an issue.
