### ISSUE TITLE
Implement support for worker code as blob url

### ISSUE THREAD

**Issue by tyt03538** [josdejong/workerpool#46]
I have a script example1.min.js in my page on domain www.example1.com, which initiates a workerpool by executing workerpool.pool('https://www.example2.com/worker.min.js'). However, the browser does not allow it due to XSS reasons.

Do you have any suggestions on resolving this issue?

**Comment by josdejong** [comment]
These sort of CORS issues can be difficult. As far as I know (but I'm no CORS expert) you either have to host both website and worker on the same domain or have to configure the server to allow this cross site script of the worker.

**Comment by tyt03538** [comment]
Thanks for the reply.

After some trials and errors, I have referenced a [gist](https://gist.github.com/roman01la/e7a7b879698574c45ca0) and made it work:

1. Fire a GET request to retrieve the scripts
2. Create a blob out of the script string
3. Create a blob url using window.URL.createObjectURL()
4. Initiate the workerpool with the blob url

The only difference is that I use axios rather than raw xhr to fetch the script.

Do you think it is a good idea to incorporate this mechanism to workerpool when the script url is of different domain?

**Comment by josdejong** [comment]
Ah, that's a creative solution :)

I think this case is too specific to accomodate for in the library. But if I understand it correctly, you can simply pass the created blob as script to the workerpool, so there is no need to integrate anything in the workerpool library itself? I guess you could create a separate npm library get-script-as-blob or something like that?

**Comment by tyt03538** [comment]
I have tried to put the blob directly to initiate a worker but it does not work though...

I have come across another lib called greenlet and it seems that it also has to create a blob url for similar reasons.

**Comment by josdejong** [comment]
Thinking about it, it indeed may make sense to add support for blob urls. For example to allow packaging your worker code in a serialized format in your frontend code.

@tyt03538 shall we change the title of this issue to something like "Implement support for worker code as blob url"?

**Comment by josdejong** [comment]
I think this is a duplicate of #23. Let's close this issue in favor of the older one.
