### ISSUE TITLE
Uncaught TypeError: Cannot read properties of null (reading 'id')

### ISSUE THREAD

**Issue by mmcardle** [josdejong/workerpool#469]
Hi 

Great library! I use it in many projects.

Have you ever seen an error that looks like this. 

![Screenshot 2024-09-27 at 16 50 31](https://github.com/user-attachments/assets/b8ad9ca0-dc38-4cff-8008-b54967f673fd)
![Screenshot 2024-09-27 at 16 50 40](https://github.com/user-attachments/assets/ffdda5e3-d23c-44a0-89cd-e2eceee8c10a)

I think it comes from the line of code.
https://github.com/josdejong/workerpool/blob/0d1506a6429eb292ba293cee6fca030a64febe47/src/WorkerHandler.js#L272

It happens  after many successfully executed long running tasks. A few fail with this error.

I am happy to try and debug and produce a fix if needed, but if there are any pointers beforehand that would be appreciated.

**Comment by josdejong** [comment]
Thanks for reporting @mmcardle . That sounds like there is a bug that does not correctly finishes tasks somehow. Help debugging this would be very welcome, without a way to reproduce the issue there isn't much I can do.

**Comment by josdejong** [comment]
Closing due to a lack of response. Please reopen if needed.
