### ISSUE TITLE
Possible to import libraries into Worker?

### ISSUE THREAD

**Issue by stoplion** [josdejong/workerpool#47]
Is it possible to import libraries into a Worker?

Worker
```
import memoize from 'fast-memoize';
import parseLine from './parse_line';
const parseLineMemoized = memoize(parseLine);

export default function parseLines(linesStr, varTable) {
  const lines = linesStr.split(/\n/);

  return lines.map((lineText, lineNum) => {
    return {
      lineNum,
      lineText: parseLineMemoized(lineText, varTable),
    };
  });
}
```

Using the worker
```
    pool.exec(parseLines, [linesStr, varTable])
      .then((result) => {
      })
      .catch((err) => {
        console.log(err)
      });
```

Getting a `parseLineMemoized is not defined at eval`

**Comment by josdejong** [comment]
Yes, I think you can generate a bundle containing your worker file, similar to how you create a .js bundle for a web application with webpack for example.

**Comment by stoplion** [comment]
Trying to get it working with Webpack, seems that the imported libs are not there for some reason..
https://codesandbox.io/s/xry123z9qq

**Comment by josdejong** [comment]
I think the reason your example doesn't work is because it would pass a function `default function(linesStr)` to a default worker, but the function is not pure, it refers to a function `parseMemoized`. 

To get something like this working, you will need to generate a bundle with a dedicated worker script containing all the functions, and create the worker pool via 
```js
const pool = workerpool.pool('/path/to/myWorker.bundle.js')
```

**Comment by Dane456** [comment]
@josdejong any idea what the `webpack.config.js` might look like for generating said bundle?

**Comment by stoplion** [comment]
There is no way to import a library, into a worker with the inline blob url way?
I've created this example with no memoized function.
https://codesandbox.io/s/0qn16zkk1v

**Comment by josdejong** [comment]
> There is no way to import a library, into a worker with the inline blob url way?

I haven't tried it. It may work already creating a blob url. See #23

**Comment by stoplion** [comment]
I mean like the `pool.exec` way. 
The example I linked to is showing `MathJS` as undefined.

**Comment by josdejong** [comment]
The tasks in a worker are executed in a separate process, and don't have access to the mathjs instance you have loaded in memory in the main process.

From the docs https://github.com/josdejong/workerpool#offload-functions-dynamically:

> Note that both function and arguments must be static and stringifiable, as they need to be send to the worker in a serialized form. In case of large functions or function arguments, the overhead of sending the data to the worker can be significant.

**Comment by stoplion** [comment]
Sorry, not sure I explained it correctly. 

In this example here: https://codesandbox.io/s/0qn16zkk1v

I've imported mathJS **directly** in the worker itself. But, mathJS is undefined still. Is this the expected behavior? 

I know that the main thread and window global is not available in the worker itself, but libraries imported into the worker I though would be..

**Comment by josdejong** [comment]
In your example, you load mathjs in the file `solve.js`, but the file is still loaded in the main tread, and when stringifying the function `solve` it will lose the memory pointer to mathjs. I think what you want to do is create a dedicated worker and load mathjs there:

Docs: https://github.com/josdejong/workerpool#dedicated-workers

**Comment by stoplion** [comment]
Thanks!

**Comment by josdejong** [comment]
:+1:

**Comment by abhishekmatta999** [comment]
Hi I want to use it in electron + Vue js. Can I use it ?
If Yes, Can you confirm that I can call an external function inside the worker which uses npm packages like realm.

**Comment by josdejong** [comment]
> Hi I want to use it in electron + Vue js. Can I use it ?

I guess so, workerpool can work in the browser and in nodejs

> If Yes, Can you confirm that I can call an external function inside the worker which uses npm packages like realm.

Yes but you'll need to create a bundle for your worker, see #189

**Comment by sedghi** [comment]
> In your example, you load mathjs in the file `solve.js`, but the file is still loaded in the main tread, and when stringifying the function `solve` it will lose the memory pointer to mathjs. I think what you want to do is create a dedicated worker and load mathjs there:
> 
> Docs: [josdejong/workerpool#dedicated-workers](https://github.com/josdejong/workerpool#dedicated-workers)

@josdejong I followed your suggestion to have a dedicated worker here https://codesandbox.io/s/mathjs-with-rollup-forked-s79xhz?file=/src/index.js

But not getting as expected results as you say. Any comment on this?

**Comment by josdejong** [comment]
@sedghi having web workers in a project requires quite some smartness form the bundler. I know that Webpack can do this, and Vite too, but I'm not sure about Rollup. So: it may be that you need a different bundler, or need to configure it correctly. Also, I've seen Vite being able to correctly bundle web workers but only when building the project, and not in development mode with hot-reloading.

**Comment by NotoriousPyro** [comment]
If you use tsup to compile to JS files, the imports work fine. Though I do this for a node JS app, not in the web.

You could then just reference the tsup'd file as the worker.
