### ISSUE TITLE
task.cancel() race condition? 

### ISSUE THREAD

**Issue by pcace** [josdejong/workerpool#476]
Hi there, i am trying to find  a solution for workers not correctly disposing memory. 

i am having this issue here: 

```
task
  .then((result) => {
    // task?.cancel() somehow leads to race condition,
    // terminating the worker before the next queued task can use it
    // if we do not cancel here, the worker memory grows continously
    // and only sometimes does garbage collection,
    // probably when queue / pending tasks for worker are empty

    task?.cancel()
    return result
  })
  .catch((e) => {
    console.log(e) // if it runs in an error, this is the message: "Worker is terminated"
    throw e
  })

```

so my issue is the task?.cancel() line: 

with this line, everything gets properly cleaned up. without this line one worker will stay open and not free up the memory. 

is there something wrong with the cancel() command or how can i free up all memory, once no worker is running anymore? 

thanks a lot!

**Comment by josdejong** [comment]
Workers are kept alive on purpose. It takes time to initialize a new worker, and creating a new worker for every task and destroying it afterwards would give a terrible performance. The `task.cancel()` method will only cancel the task at hand. It will not terminate workers. If you want to terminate all your workers, you can do `await pool.terminate()` and then create a fresh, new pool if needed.
