### ISSUE TITLE
Error in testing using Vitest

### ISSUE THREAD

**Issue by PratikDarak** [josdejong/workerpool#477]
I am getting the following error when testing a component using workerpool in Vitest:
```
TypeError: 'postMessage' requires 2 arguments: 'message' and 'targetOrigin'
    at window.postMessage (/builds/Cimpress-Technology/Embroidery/stitchx-2.0/node_modules/jsdom/lib/jsdom/browser/Window.js:785:13)
    at Object.worker.send (/builds/Cimpress-Technology/Embroidery/stitchx-2.0/node_modules/workerpool/src/worker.js:56:50)
    at Object.worker.register [as add] (/builds/Cimpress-Technology/Embroidery/stitchx-2.0/node_modules/workerpool/src/worker.js:354:10)
    at Object.worker (/builds/Cimpress-Technology/Embroidery/stitchx-2.0/node_modules/workerpool/src/index.js:39:10)
    at /builds/Cimpress-Technology/Embroidery/stitchx-2.0/wasm/api_worker.ts:34:12
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at InlineWorkerRunner.runModule (file:///builds/Cimpress-Technology/Embroidery/stitchx-2.0/node_modules/vite-node/dist/client.mjs:399:5)
    at InlineWorkerRunner.directRequest (file:///builds/Cimpress-Technology/Embroidery/stitchx-2.0/node_modules/vite-node/dist/client.mjs:381:5)
```

Vitest config:
```
test: {
	globals: true,
	include: ["**/*.spec.ts"],
	environment: "jsdom",
	setupFiles: ["@vitest/web-worker"],
	silent: true
},
```

Workerpool creation:
```
// Create pool of workers for "wasm_worker" script
export const wasmWorkerPool = workerpool.pool(WasmWorkerURL, {
	minWorkers: "max",
	maxWorkers: optimum_wasm_workers,
	workerType: "web",
	workerOpts: { type: import.meta.env.PROD ? undefined : "module" }
});

// Create pool of workers for "api_worker" script
export const apiWorkerPool = workerpool.pool(APIWorkerURL, {
	minWorkers: "max",
	maxWorkers: optimum_api_workers,
	workerType: "web",
	workerOpts: { type: import.meta.env.PROD ? undefined : "module" }
});
```

Unfortunately I am not sure how to reproduce this but it is only happening while running the test pipeline in CI-CD.

I have a hunch that it might be due to this line: https://github.com/josdejong/workerpool/blob/6bf949e2db2e909522d50c7236390c46b87ddf2f/src/worker.js#L61 where there is an extra space between `postMessage` & `(message)`.

Similar Issue reported earlier: https://github.com/josdejong/workerpool/issues/435#issue-2209721404

Thank you for your help!

**Comment by josdejong** [comment]
Thanks for reporting. 

Maybe Vitest is mixing up two different implementation of `postMessage:

- Worker `postMessage`, see https://developer.mozilla.org/en-US/docs/Web/API/Worker/postMessage
- Window `postMessage`, see https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage

If that is the case, it may help if we replace `postMessage` with `self.postMessage`. @PratikDarak is it possible for you to try changing that in the workerpool code? If not, I can simply release a fix and after that we can see if it actually works.

**Comment by PratikDarak** [comment]
I gave it a try, but it doesn't seem to resolve the issue. The main problem appears to be that `self` (or `this`) is referring to the `window` object instead of `DedicatedWorkerGlobalScope`.  

I suspect this might have something to do with how Vitest is running the tests. As you know, I'm using the "jsdom" environment along with the "@vitest/web-worker" package to add web worker support to jsdom.  

It’s possible that "jsdom" is causing this behavior, but I’m not entirely sure. Do you have any thoughts or suggestions? Would love to hear your input!

**Comment by josdejong** [comment]
Hm, ok. Thanks for testing this out.

We somehow have to explain to Vite/Vitest that the file is a worker. In [`@vitest/web-worker`](https://www.npmjs.com/package/@vitest/web-worker) I see the use of an import like `import MyWorker from '../worker?worker'`, note the `?worker` at the end. I don't think this flag [is standardized](https://stackoverflow.com/questions/75461018/what-does-a-question-mark-mean-in-a-typescript-import-statement) and I guess this breaks in regular JavaScript, but maybe Vite uses that to recognize workers?

Or maybe we need to apply certain TypeScript config or Vite config like briefly discussed here: https://vite.dev/guide/env-and-mode#intellisense-for-typescript

**Comment by josdejong** [comment]
Maybe this Stackoverflow discussion helps too: https://stackoverflow.com/questions/56356655/structuring-a-typescript-project-with-workers

**Comment by PratikDarak** [comment]
Thanks, @josdejong, for taking a look at this. I’ll follow up with the Vitest team to investigate further. I really appreciate your help — thank you! 🙏
