### ISSUE TITLE
Why so many threads?

### ISSUE THREAD

**Issue by vladf90** [josdejong/workerpool#48]
I have a workerpool with minWorkers 2 and maxWorkers 2. After offloading some work to the pool I can see in htop that the 2 workers spawned multiple threads. As I understood from doc there should be only 2 workers which will process the incoming work. Is this normal?

PS: I added a screenshot with how htop looks for the workerpool at this [link](https://imgur.com/yT4r0Fl)

**Comment by josdejong** [comment]
`minWorkers` and `maxWorkers` specify the number of *processes* (white text color in htop), node.js itself creates some *threads* internally (green text color in htop), I see 6 threads on my machine when running a simple workerpool example. In htop you can switch to see processes only by pressing `H`.
