### ISSUE TITLE
Feauture: 1 pool that manages multiple workers

### ISSUE THREAD

**Issue by stefanpenner** [josdejong/workerpool#53]
Currently 1 custom worker results in 1 pool, but in my usecase (a build system) I would prefer to have 1 pool where I could register multiple workers, similarly to how I can currently register multiple methods.

This would prevent an unessary number of sub processes/threads, that typically remain dormant, as we would begin reusing existing pools subproceses/threads.

If this idea sounds reasonable, I will provide a PR. If not, it can be implemented in user-land, but It seems more appropriate as part node-workerpool.

Let me know!

**Comment by josdejong** [comment]
@stefanpenner I'm not sure what you mean, right now `1` pool will create multiple worker instances if needed, and the min and max number of workers can be configured with `minWorkers` and `maxWorkers`. 

Do you mean register multiple worker scripts with a single pool? How would that work exactly?

**Comment by stefanpenner** [comment]
> Do you mean register multiple worker scripts with a single pool? 

Yup, exactly.

> How would that work exactly?

From user-land, I would create a dedicate worker, which supported registering additional modules on the fly.  This would allow a single pool of node processes to be used to do multiple different kinds of work.

```js
// meta-worker.js
const workerpool = require('workerpool')

workerpool.worker({
  exec(script, fnName args) {
     return require(script)[fnName](...args);
  }
});
```


```js
// index.js
const workerpool = require('workerpool');
const pool = workerpool.pool(__dirname + './meta-worker.js');

pool.exec('exec', __dirname + '/babel-6-worker.js', 'transformSync', args);
pool.exec('exec', __dirname + '/handlebars-worker.js', 'transformSync', args);
pool.exec('exec', __dirname + '/xyz-worker.js', 'fn', args);
```


```js
// babel-6-worker.js
module.exports = {
  transformSync(args) {
    return require('babe').transformSync(...args);
  }
}
```


---

Now although this can clearly be done in user-land, it really doesn't feel like an uncommon pattern to want/need. So I wanted to see if you had interest in providing the functionality by default.

A hypothetical API:


```js
const pool = workerPool.sharedWorkerPool();

pool.execWorker(script, fnName, args); // optional new api
pool.exec(script, fnName, args); // extend existing API to function differently if arguments.length === 3
```

---

Ultimately though, if you believe this is better handled in user-land, I have no issue with that. I do not believe I am blocked at all.

**Comment by josdejong** [comment]
Thanks for working out this idea Stefan, I understand what you mean.

I think I prefer to keep workerpool simple and focused. I have the feeling that supporting this would complicate both API as well as implementation without much benefits. 

Some thoughts:

- It feels a bit analogous to having a list of (dynamic) `<script />` tags in an HTML page, the way we used to work with long time ago. Nowadays we create a single bundle (and possibly code splitting). I have the feeling that for worker scripts we can best do the same: create a single bundle containing all you want the worker to do.
- To have a single worker handle multiple scripts, I guess it has to switch run-time between different scripts or risk issues with collisions between globals and state defined in the different scripts. I'm not sure if that is possible at all and what compications there will be.

**Comment by stefanpenner** [comment]
> * Nowadays we create a single bundle (and possibly code splitting). I have the feeling that for worker scripts we can best do the same: create a single bundle containing all you want the worker to do.

Unfortunately, similarly to bundles. Often times, especially for a big system you may have more bundles then workers, but still want to limit the number of workers globally.

But I don't disagree that this doesn't need to live in core. I will implement it in user-land :)

**Comment by josdejong** [comment]
:+1: 

> Often times, especially for a big system you may have more bundles then workers, but still want to limit the number of workers globally.

Yes I can imagine that, but wouldn't it be possible to bundle the bundles, so 1 worker has 1 bundle with _all_ the functionality you need?

**Comment by stefanpenner** [comment]
@josdejong unfortunately not.
