### ISSUE TITLE
Is pool.terminate async?

### ISSUE THREAD

**Issue by mramato** [josdejong/workerpool#56]
The documentation treats `pool.terminate` as synchronous, but in practice (at least under Node.js) it returns a Promise.

It makes sense to me that it would be asynchronous, but I wanted to confirm before updating my own code.

If it is async, I'd be happy to open a PR to make sure the doc matches.

Thanks for an awesome library!

**Comment by josdejong** [comment]
@mramato thanks, you're right. The `terminate` method returns a promise but this is not documented anywhere. A PR to improve the docs would be welcome!

**Comment by mramato** [comment]
Thanks, will do.
