### ISSUE TITLE
request new feature: 

### ISSUE THREAD

**Issue by matth-c3** [josdejong/workerpool#62]
Hello, 

Would it be possible to add 2 methods : 

- to tag the workers; that could be useful for the next one. 

- to restart / renew a specific workers or proxy to a specific worker

The use case I see is if code change, it could slowly restart each worker to implement the new method

Thank you.

**Comment by josdejong** [comment]
@matth-c3 thanks for your suggestion. 

Would it work for your case to simply call `pool.terminate()`? That will gracefully kill all workers after they finish there current operation. After that you can simply keep calling methods, and new workers will be spawned automatically.

**Comment by matth-c3** [comment]
Hello @josdejong , yes i adapted it to my need. 

Thaanks
