### ISSUE TITLE
Workerpool Worker terminated Unexpectedly exitCode: `1` 

### ISSUE THREAD

**Issue by stoplion** [josdejong/workerpool#64]
Trying to get a dedicated worker to work in Node/Express with a simple example. Constantly getting a ...
```
Workerpool Worker terminated Unexpectedly exitCode: `1` signalCode: `null` workerpool.script: `path/to/worker/test.worker.js` spawnArgs: `/usr/local/bin/node,--inspect=43210,path/to/worker/test.worker.js` spawnfile: `/usr/local/bin/node` stdout: `null` stderr: `null`
```
Here is a sample repo of the issue:
https://github.com/stoplion/worker-test

Is there anything I am missing with the setup?

**Comment by stoplion** [comment]
nm I found the answer!

**Comment by yvanwangl** [comment]
@stoplion hey bro, how to fix this problem?
