### ISSUE TITLE
How to import external function to Worker?

### ISSUE THREAD

**Issue by Kaa10** [josdejong/workerpool#66]
Hello!
I am currently in a project that involves:
Electron v4.1.4
Vue v2.6.10
Node v10.11.0
Vuetify v1.5.9
Chromium v69.0.3497.128
V8 v6.9.427.31-electron.0
NPM Packages:
 - ws v6.1.0 (Websocket)
 - pg v7.4.3 (postgreSQL)

Case study:
I need to create a Worker in a separate file or in the same component. "Vue" or ".js" that receives an "asynchronous" function. This function creates a Websocket connection with a file named "server.js" running through "pm2" on the server.

Situation:
Test the "workerpool" package on electron within a .vue component and it works perfectly. However I can not pass an external function to the worker.

The following examples:
```   
    Example 1 -> RUN OK!
   //File - Login.vue
   TEST_WORKER: async function () {
       var workerpool = require ('workerpool');
        var pool = workerpool.pool ();

        function add () {
          let element
          for (let index = 0; index <1000000000; index ++) {
            element = index
          }
          return element
        }
   
        try {
          let x = await pool.exec (add)
          console.log (x)
        catch (error) {
          console.log (error)
        }
      }
  ```
```
  Example 2 -> DON'T RUN!
  File - Login.vue

  TEST_WORKER: async function () {
       var workerpool = require ('workerpool');
        var pool = workerpool.pool ();   
        try {
          let x = await pool.exec (this.EXTERNAL_FUNCTION_WORKER())
          console.log (x)
        catch (error) {
          console.log (error)
        }
      }

EXTERNAL_FUNCTION_WORKER: function () {
          let element = 0
          for (let index = 0; index <1000000000; index ++) {
            element = index
          }
          return element
}
```
Situation 2:
I can not reference the Worker path.
Example:
```
 var pool = workerpool.pool ('/ workers / worker.js');
```
The file is in a top level folder and app does not find, error 404 is generated.
How do I proceed?

appreciate!

**Comment by josdejong** [comment]
@Kaa10 I'm not sure if I fully understand you. 

Have you had a look at an example like https://github.com/josdejong/workerpool/blob/master/examples/browser/dedicatedWorker.html ?

Can you create a small demo on https://codesandbox.io or so showing how to reproduce your issue?

**Comment by Kaa10** [comment]
Hi @josdejong! I'm going to try that: https://github.com/josdejong/workerpool/blob/master/examples/browser/dedicatedWorker.html 

Please, please leave this question open! I will perform some tests and any questions I have I will do through the suggestions that you have informed!
Thank you!

**Comment by Kaa10** [comment]
![code_1](https://user-images.githubusercontent.com/49574544/56618947-63141280-65fa-11e9-8264-6fe19062184f.PNG)
![error](https://user-images.githubusercontent.com/49574544/56618961-6909f380-65fa-11e9-9c51-6e881d75fa15.PNG)

**Comment by josdejong** [comment]
Since you create the worker like `workerpool.pool('worker.js')` it will expect the file `worker.js` in the root of your server, at `http:localhost:9080/worker.js`. Apparently it is not there. Your probably have to make sure your build script copies and/or bundles your file `worker.js` too.

Alternative idea (not yet supported): see #46

**Comment by Kaa10** [comment]
Ok, thanks! I'm going to make that "http:localhost:9080/worker.js"

**Comment by Kaa10** [comment]
I tried putting the worker.js in the src root folder and nothing. Inside the src folder there are two grazing of the electron to renderer and main that I also put but the error continues. On the suggestion of question # 46 I found it too complicated to implement in my app. I have tried other packages with npm but without success. I even opened a question for SimulatedGREG / electron-vue on GitHub because it's the boilerplate I use but I still have not gotten a response. Simply what I need is to add web workers to database query tasks and maybe generate PDF reports in the future.

**Comment by josdejong** [comment]
`workerpool` is only a simple wrapper around web workers and child_processes. Maybe it helps to figure out how to get a plain web worker or child_process in Electron working?

**Comment by Kaa10** [comment]
I'll try with child_process as you suggested. I'm anxious for nodejs worker-threads to become stable perhaps in version 13 and ready for production as I believe it's to implement. Please leave the topic still open. thank you

**Comment by stoplion** [comment]
related to #47

**Comment by Kaa10** [comment]
OK! Thanks!

**Comment by Kaa10** [comment]
I was able to implement the library to Electron-vue, however, I am not able to implement asynchronous worker with promises, as this error is displayed:
![async worker](https://user-images.githubusercontent.com/49574544/57039354-cae9df00-6c32-11e9-8318-2bf8356a83c1.PNG)
![error](https://user-images.githubusercontent.com/49574544/57039359-cd4c3900-6c32-11e9-8665-be0046415d9e.PNG)

**Comment by josdejong** [comment]
That's good news that you got things working in your setup.

I think in your async function you have to return a Promise, like:

```js
async function () {
  return Pool.exec(...)
}
```

**Comment by Kaa10** [comment]
> That's good news that you got things working in your setup.
> 
> I think in your async function you have to return a Promise, like:
> 
> ```js
> async function () {
>   return Pool.exec(...)
> }
> ```


I tried to do as suggested but the following error occurs:

**Comment by Kaa10** [comment]
I tried this other way and also the error
![erro app](https://user-images.githubusercontent.com/49574544/57113190-d95ef600-6d19-11e9-8080-aeba90bbe388.PNG)
![erro worker async](https://user-images.githubusercontent.com/49574544/57113192-d95ef600-6d19-11e9-9254-f53c4f0ffdd5.PNG)
![erro debug](https://user-images.githubusercontent.com/49574544/57113191-d95ef600-6d19-11e9-9af1-3f0c751998ff.PNG)

**Comment by josdejong** [comment]
The error message says "worker.asyncAdd is not a function". Did you implement the function in your worker? (I don't see the function in the contents of `worker1.js` that you post),

Maybe you can take one of the examples provided with workerpool and go from there?
https://github.com/josdejong/workerpool/blob/master/examples/workers/asyncWorker.js

**Comment by Kaa10** [comment]
I corrected, but now this error happens:
![component Vue](https://user-images.githubusercontent.com/49574544/57184725-fcaeb000-6e95-11e9-9016-f444f18aaabb.PNG)
![worker1](https://user-images.githubusercontent.com/49574544/57184729-fd474680-6e95-11e9-9763-769c4158dbe9.png)
![erro app](https://user-images.githubusercontent.com/49574544/57184728-fd474680-6e95-11e9-86d6-60d3fdb0ad4d.PNG)

**Comment by josdejong** [comment]
You're mixing "offloading a function" with "dedicated worker". Please study the examples of dedicated workers closely: https://github.com/josdejong/workerpool#dedicated-workers

Your worker should look like:
```js
function asyncAdd (a, b) {
  // ...
}

workerpool.worker({
  asyncAdd: asyncAdd
});
```

And your main process like:
```js
const result = pool.exec('addAsync', [2, 3]) // method name is a string
```
Alternatively, you can create a proxy to the worker in your main process:
```js
const worker = await pool.proxy()
const result = worker.asyncAdd(3, 4.1);
```

**Comment by Kaa10** [comment]
Actually what is happening is that the Webpack can not make the "require.resolve ()" function work, and so I need to export a node module to the "pool.exec ()" function instead of directly referring the worker to the method "Workerpool.pool ('./ workers.js') or" Workerpool.pool ('require.resolve (./ workers.js')).
The boilerplate I use uses Webpack and have already tried several other npm packages, but to no avail. 
I've reviewed a few hundred times to see if I can adapt to boilerplate but to no avail.
My main problems is:
- import the worker to the Workerpool.pool () function.

If I execute the workers without importing the javascript file, the workers works, according to the photo.
![1](https://user-images.githubusercontent.com/49574544/57194554-a6d21a80-6f1e-11e9-8afa-cf82698c5049.png)
![2](https://user-images.githubusercontent.com/49574544/57194555-a6d21a80-6f1e-11e9-9d26-07c35c49eb55.png)

Do you suggest a plugin, tool or have you ever had a situation so maybe you can give an opinion?

**Comment by josdejong** [comment]
Sounds like #46 and/or #47?

**Comment by Kaa10** [comment]
OK, Thanks!

**Comment by josdejong** [comment]
:+1:
