### ISSUE TITLE
Typescript class ready

### ISSUE THREAD

**Issue by sayh2511** [josdejong/workerpool#68]
Hi,

I wanted to Offload functions dynamically, but If I do this with a Typescript Object, it breaks with:

> TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'UserDAO'
    |     property '_storage' -> object with constructor 'Object'
    |     property 'username' -> object with constructor 'UserEntity'
    |     ...
    |     index 0 -> object with constructor 'DeviceEntity'
    --- property 'userDAO' closes the circle
    at JSON.stringify (<anonymous>)
    at ChildProcess.target._send (internal/child_process.js:778:25)
    at ChildProcess.target.send (internal/child_process.js:676:19)

Well I expected that I can just insert my Device Object (class) and It will just pass it to the generated worker. My Code:
```js
function adder (number1, number2, device) {
  console.log(number1, number2, device);

  return number1 + number2;
}

class WorkerService {

  private static instance;

  public pool = workerPool.pool();

  constructor() {
  }
  public executeAdder(device: IDevice): void {
    this.pool.exec(adder, [10, 3, device]).then(result => {
      console.log(result);
    }).catch(err => {
      console.error(err);
    });
  }

}
```

Hope you can make this working soon
Best Regards

**Comment by josdejong** [comment]
To pass the function arguments to the worker, the data must be serialized and JSON is used for this. The error you get suggests your data model contains is a circular reference making it impossible to serialize. 

I think you can either change the data you have to pass to regular JSON, or create your own serializer and deserializer to pass arguments to your worker, like `this.pool.exec(adder, [10, 3, serializeDevice(device)])`, and a deserializer on the other side.

**Comment by sayh2511** [comment]
ahh thank you, you are right, but another problem is, that I cant use a typescript class function as the Offload function. I also tried to make it static, but I always get : 
SyntaxError: Unexpected token {
    at Function.run (xxx/node_modules/workerpool/lib/worker.js:79:25)
    at process.<anonymous> (xxx/node_modules/workerpool/lib/worker.js:98:27)
    at process.emit (events.js:200:13)
    at emit (internal/child_process.js:876:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:9)

Hope you can also help me here :)
Best Regards

**Comment by josdejong** [comment]
Hm I'm not sure the like [worker.js:79:25](https://github.com/josdejong/workerpool/blob/master/lib/worker.js#L79) is the line executing the function with arguments in the worker. Not sure why it throws a `SyntaxError: Unexpected token {`. Can you create a minimal example in codesandbox or jsbin to demonstrate the issue?

**Comment by sayh2511** [comment]
Hi,

I couldn't reproduce it in codesandbox, because it hasn't throw a error. You can instead paste the code below in a js file and run it. I Hope you can find a solution for it.

I see that there is spawning a new worker but then the error occurs.

`const workerpool = require("workerpool");
const pool = workerpool.pool();

class Calc {
  normalAddFunction(num1, num2) {
    console.log(num1, num2);
    return num1 + num2;
  }

  async workerAddFunction(num1, num2) {
    // Error happens if I give the normalAddFunction as static or normal
    console.log(num1, num2);
    return await pool.exec(this.normalAddFunction, [num1, num2]).catch(err => {
      console.error(err);
    });
  }
}

async function print() {
  const calcClass = new Calc();
  const result = calcClass.normalAddFunction(2, 3);
  const workerResult = await calcClass.workerAddFunction(10, 20);

  console.log(result, workerResult);
}

print();
`

**Comment by josdejong** [comment]
It looks like the way class methods are serialized is not suitable to parse and run them as a standalone function:

```
console.log(this.normalAddFunction.toString())
// normalAddFunction (num1, num2) {
//     console.log(num1, num2);
//     return num1 + num2;
// }
```
here, the stringified output is missing the `function` keyword right before `normalAddFunction`. 

In general, class methods depend upon state of the class they belong to, so in general you can't execute class methods in a worker. Only pure functions can be serialized and executed on a worker. So you can either rewrite your code such that you have a pure, standalone function instead of a class method, or you can create a dedicated worker which instantiates you class and executes methods on it.

**Comment by sayh2511** [comment]
Okay Thank you very much!!
