### ISSUE TITLE
minWorkers is not acting as documented

### ISSUE THREAD

**Issue by Srokap** [josdejong/workerpool#81]
I have the case where I tried to spin up pool with following options:
```
const numCPUs = 5
workerpool.pool(path, {
  minWorkers: 'max',
  maxWorkers: numCPUs
}
```
I expected to see 5 workers spinned up, but I saw 3 instead (machine has 4 CPUs).

It seems that [actual implementation](https://github.com/josdejong/workerpool/blob/9d99f2ae74b6d3c71b88f69673af4aab09f740b0/lib/Pool.js#L42) is looking at CPU count instead of copying maxWorkers value as implied by the [documentation](https://github.com/josdejong/workerpool/blob/master/README.md#pool)

```
minWorkers: number | 'max'. 
The minimum number of workers that must be initialized and kept available. 
Setting this to 'max' will create maxWorkers default workers (see below).
```

**Comment by josdejong** [comment]
Ah, you're right, in that case I think it should just pick `this.maxWorkers`.
