### ISSUE TITLE
`worker.send = process.send.bind(process)...  TypeError: Cannot read property 'bind' of undefined`

### ISSUE THREAD

**Issue by loganpowell** [josdejong/workerpool#82]
I'm on Windows 10 and this may be due to that (I remember the days when windows was the first thing to get oversight, but alas)...

I'm getting this error running on node `10.15.3`:
```
...node_modules\workerpool\lib\worker.js:42
worker.send = process.send.bind(process);
                               ^
TypeError: Cannot read property 'bind' of undefined
```

I looked through the other issues and couldn't find anything related. I could just be doing something stupid. It works fine in my Quokka REPL...

Could it be that I'm using another `const externalLibrary = require('externalLibrary')` in the `worker.js` file (imported)

Not sure if it's related, but here's the docs on the subject:

https://nodejs.org/api/child_process.html#child_process_options_stdio

**Comment by loganpowell** [comment]
I'm an idiot. I was trying to call the worker.js file instead of the file that imported it :P

**Comment by josdejong** [comment]
No problem :)
