### ISSUE TITLE
Uses browser mode in Jest

### ISSUE THREAD

**Issue by just-paja** [josdejong/workerpool#85]
I'm having trouble testing my API outputs in Jest. I always get 

> WorkerPool: Web workers not supported by the browser

In version 3, I would mock the `workerpool/lib/environment` module and set it to "node" mode. Version 4 seems to be utilizing webpack and the environment module is no longer exposed. Is there any way to force workerpool to run in "node" mode?

As a workaround, I use `global.Window = undefined` in my jest setup, but I see it as a hack.

Thank you for this amazing library.

**Comment by just-paja** [comment]
Actually, this is related to #74

**Comment by josdejong** [comment]
That's an interesting case. So I guess you have a web application (using web workers) but do testing in Jest on node.js. 

It's indeed a use case of #74. 

Instead of #74, it may be even simpler and more powerful to extend the current option `nodeWorker`: rename it to `workerType` allowing you to select 'web' | 'process' | 'thread' | 'auto' (all options for both browser and node.js). Then you have full control over what type of worker is selected, currently you don't have full control.

**Comment by just-paja** [comment]
> So I guess you have a web application (using web workers) but do testing in Jest on node.js.

It does not even have to be a web application. Jest (by default) runs the tests in jsdom environment, so it is kind of both node and browser. I have an electron application and use Jest to test both frontend and backend.

Made a reprorepo https://github.com/just-paja/workerpool-jest-repro

**Comment by josdejong** [comment]
ah, I hadn't realized that.

Thanks for sharing workerpool-jest-repo, that will make it easy.

**Comment by josdejong** [comment]
Pavel I've just published `workerpool@5.0.0`, which should address your issue with testing in Jest. 

- There is a new option `workerType` (replacing `nodeWorker`), which allows you to explicitly select a type of worker without any magic.
- The environment detection (node/browser) is improved.

Would be great if you can give this a try. I've tested against your demo repo, that works better now (you have to change the script name from `worker` to `worker.js`).

**Comment by just-paja** [comment]
@josdejong, I updated the repro and the issue seems to be fixed with version 5. Thank you very much!

**Comment by josdejong** [comment]
That's good to hear, thanks for the feedback!
