### ISSUE TITLE
Support for Typescript?

### ISSUE THREAD

**Issue by alexon1234** [josdejong/workerpool#89]
I wonder if there is a roadmap to create a wrapper or something to be able to support typescript?

Currently, I am doing the following:

```
## main.ts
private readonly workersPool: WorkerPool = pool(
    `${__dirname}/worker.js`
  );

workersPool.exec('hello', ['world'])

## worker.js 

const path = require('path');

require('ts-node').register();
require(path.resolve(__dirname, './worker.ts'));


## worker.ts

import { worker } from 'workerpool';

worker({
  hello: (message: string) => `hello ${message}`,
});

```

**Comment by josdejong** [comment]
I think there are type definitions for workerpool on DefinitelyTyped?

**Comment by alexon1234** [comment]
Yes, I think it would make more sense.
Thanks for replying and for all the work you have done

**Comment by josdejong** [comment]
:+1: thanks Alejandro.

**Comment by RodolfoSilva** [comment]
With the **piscina** library, I solved this by doing something like this:

**worker.ts**
```ts
import path from 'path';

export const filepath = path.resolve(__filename);

export default async function add(a: number, b: number) {
  return a + b;
};
```

**main.ts**
```ts
import Piscina from 'piscina';
import worker from './worker';

const piscina = new Piscina({
  filename: worker.filepath,
});
```

I don't know if this is the right way to do it, but it works for me.
It would be nice to have something like that in `workerpool`.

**Comment by RodolfoSilva** [comment]
With the **piscina** library, I solved this by doing something like this:

**worker.ts**
```ts
import path from 'path';

export const filepath = path.resolve(__filename);

export default async function add(a: number, b: number) {
  return a + b;
};
```

**main.ts**
```ts
import Piscina from 'piscina';
import worker from './worker';

const piscina = new Piscina({
  filename: worker.filepath,
});
```

I don't know if this is the right way to do it, but it works for me.
It would be nice to have something like that in `workerpool`.

@josdejong

**Comment by josdejong** [comment]
Ah, priscina looks like, I hadn't seen it before. I've added it to the list with related libraries in the readme.

Yes something like that would be nice indeed :) I have no idea how much work it would be to implement TypeScript support on this level. I will not have time for this my self any time soon, help would be very welcome.

**Comment by thiagodpf** [comment]
Hey guys!

When I came across this thread I thought it would be interesting to leave a tip on how I solved this typescript issue in the workerpool :smiley: 

to contextualize, I am using the `workerpool` lib with _Node.js_, through the [worker_threads](https://nodejs.org/api/worker_threads.html#new-workerfilename-options) and in the _development | testing_ environment (where we perform debugging) I use the `ts-node` module to transform the typescript (when preloading the file containing the worker script), while in the _production_ environment, the typescript has already been transformed into javascript and I do not need the module anymore.

The trick is to use worker_threads `execArgv` option, distinguishing whether it is necessary to transform the script given the file extension: `/\.ts$/.test(workerScriptFile)` :sweat_smile: 

`src/main.ts`:
```typescript
import workerpool from 'workerpool';

// require.resolve() accepts as parameter a "node module name"
// this way we don't have to worry about the file extension {.ts or .js after transformation}
const workerScriptFile = require.resolve(path.join(__dirname, '/worker'))

const pool = workerpool.pool(workerScriptFile, {
  workerType: 'thread',
  workerThreadOpts: {
    execArgv: /\.ts$/.test(workerScriptFile) ? ["--require", "ts-node/register"] : undefined,
  }
});

pool.exec('hello', ['world'])
```


`src/worker.ts`:
```typescript 
import { worker } from 'workerpool';

worker({
  hello: (message: string) => `hello ${message}`,
});
```

I hope this tip can help other developers who are experiencing the same problem and come across this thread using a search engine :smile:

**Comment by josdejong** [comment]
Thanks for sharing @thiagodpf!

**Comment by MJez29** [comment]
In node 22 you can also use node's `--experimental-strip-types` or `--experimental-transform-types` instead of invoking ts-node! [[more info](https://nodejs.org/en/learn/typescript/run-natively)]

```ts
workerThreadOpts: {
  execArgv: [
    "--experimental-strip-types",
    "--disable-warning=ExperimentalWarning"
  ]
}
```
